import type { ColumnDef, ForeignKeyDef, IndexDef, TableSchema } from '@tsmyadmin/shared'
import { describe, expect, it } from 'vitest'
import { rows, scripted } from '../test/scripted-conn.ts'
import { type PgTableCatalog, pgCreateStatements, pgTableCatalog } from './create-statements.ts'

/**
 * What the PostgreSQL dump writes to create a table again, from the table's description and the catalog's extra
 * parts. A wrong clause here is a table restored differently from the one dumped (found as surviving mutants).
 */

const ns = { database: 'db', schema: 'app' }
const col = (name: string, dataType: string, extra: Partial<ColumnDef> = {}): ColumnDef =>
  ({
    name,
    dataType,
    nullable: true,
    default: null,
    defaultIsExpression: false,
    extra: '',
    comment: null,
    collation: null,
    check: null,
    ...extra,
  }) as ColumnDef
const index = (name: string, columns: string[], extra: Partial<IndexDef> = {}): IndexDef => ({
  name,
  unique: false,
  primary: false,
  columns,
  type: null,
  predicate: null,
  definition: null,
  lengths: {},
  ...extra,
})
const table = (columns: ColumnDef[], extra: Partial<TableSchema> = {}): TableSchema =>
  ({
    name: 't',
    kind: 'table',
    comment: null,
    columns,
    primaryKey: [],
    indexes: [],
    foreignKeys: [],
    ...extra,
  }) as unknown as TableSchema
const catalog = (extra: Partial<PgTableCatalog> = {}): PgTableCatalog => ({
  constraints: [],
  identityOptions: new Map(),
  inherits: null,
  partitionKey: null,
  partitions: [],
  localColumns: null,
  unlogged: false,
  storage: null,
  ...extra,
})

describe('the columns of a table', () => {
  it('writes each column with its type, collation, NOT NULL and default, and the primary key last', () => {
    const out = pgCreateStatements(
      ns,
      table(
        [
          col('id', 'integer', { nullable: false }),
          col('n', 'text', { nullable: false, default: "'x'::text", collation: 'C' }),
          col('o', 'text'),
        ],
        { primaryKey: ['id'] }
      )
    )
    expect(out).toEqual([
      'CREATE TABLE "app"."t" (\n  "id" integer NOT NULL,\n  "n" text COLLATE "C" NOT NULL DEFAULT \'x\'::text,\n  "o" text,\n  PRIMARY KEY ("id")\n)',
    ])
    expect(pgCreateStatements(ns, table([col('a', 'int'), col('b', 'int')], { primaryKey: ['a', 'b'] }))[0]).toContain(
      'PRIMARY KEY ("a", "b")'
    )
    expect(pgCreateStatements(ns, table([col('a', 'int')]))[0]).not.toContain('PRIMARY KEY')
  })

  it('writes an identity column as GENERATED … AS IDENTITY with its options, and a serial one as BY DEFAULT without a default', () => {
    const cols = [
      col('a', 'integer', { extra: 'identity always', nullable: false }),
      col('b', 'bigint', { extra: 'identity by default', default: 'ignored' }),
      col('c', 'integer', { extra: 'serial', default: "nextval('t_c_seq'::regclass)" }),
    ]
    const withOptions = catalog({ identityOptions: new Map([['a', 'START WITH 1000 CACHE 10']]) })
    expect(pgCreateStatements(ns, table(cols), withOptions)[0]).toBe(
      'CREATE TABLE "app"."t" (\n  "a" integer GENERATED ALWAYS AS IDENTITY (START WITH 1000 CACHE 10) NOT NULL,\n  "b" bigint GENERATED BY DEFAULT AS IDENTITY,\n  "c" integer GENERATED BY DEFAULT AS IDENTITY\n)'
    )
    // Without the catalog (a preview) the options are left out.
    expect(pgCreateStatements(ns, table(cols))[0]).toContain('"a" integer GENERATED ALWAYS AS IDENTITY NOT NULL')
  })

  it('writes a generated column as its expression, stored or virtual, never as a default', () => {
    const out = pgCreateStatements(
      ns,
      table([
        col('s', 'integer', { extra: 'generated stored', default: 'a + 1', nullable: false }),
        col('v', 'integer', { extra: 'generated virtual', default: 'a * 2' }),
        col('g', 'integer', { extra: 'generated stored', default: null }),
      ])
    )[0]
    expect(out).toContain('"s" integer GENERATED ALWAYS AS (a + 1) STORED NOT NULL')
    expect(out).toContain('"v" integer GENERATED ALWAYS AS (a * 2) VIRTUAL')
    expect(out).toContain('"g" integer')
    expect(out).not.toContain('DEFAULT')
    expect(out).not.toContain('"g" integer GENERATED')
  })

  it('adds the table options the catalog reports: unlogged, inheritance, partitioning and storage', () => {
    const t = table([col('a', 'int')])
    expect(pgCreateStatements(ns, t, catalog({ unlogged: true }))[0]).toMatch(/^CREATE UNLOGGED TABLE "app"\."t"/)
    expect(pgCreateStatements(ns, t, catalog({ unlogged: false }))[0]).toMatch(/^CREATE TABLE "app"\."t"/)
    expect(pgCreateStatements(ns, t, catalog({ inherits: '"app"."p"' }))[0]).toMatch(/\n\) INHERITS \("app"\."p"\)$/)
    expect(pgCreateStatements(ns, t, catalog({ partitionKey: 'RANGE (a)' }))[0]).toMatch(
      /\n\) PARTITION BY RANGE \(a\)$/
    )
    expect(pgCreateStatements(ns, t, catalog({ storage: "fillfactor='70'" }))[0]).toMatch(
      /\n\) WITH \(fillfactor='70'\)$/
    )
    expect(pgCreateStatements(ns, t, catalog({ inherits: '"p"', partitionKey: 'LIST (a)', storage: 's' }))[0]).toMatch(
      /\) INHERITS \("p"\) PARTITION BY LIST \(a\) WITH \(s\)$/
    )
  })
})

describe('an inheritance child', () => {
  it('declares only its own columns, and adjusts the inherited ones afterwards', () => {
    const t = table([
      col('own', 'int'),
      col('d', 'int', { default: '5' }),
      col('s', 'int', { extra: 'serial', default: "nextval('q'::regclass)" }),
      col('i', 'int', { extra: 'identity always', default: '7', nullable: false }),
      col('n', 'int', { nullable: false }),
      col('g', 'int', { extra: 'generated stored', default: 'own + 1' }),
    ])
    const out = pgCreateStatements(ns, t, catalog({ inherits: '"app"."p"', localColumns: new Set(['own']) }))
    expect(out).toEqual([
      'CREATE TABLE "app"."t" (\n  "own" int\n) INHERITS ("app"."p")',
      'ALTER TABLE ONLY "app"."t" ALTER COLUMN "d" SET DEFAULT 5',
      `ALTER TABLE ONLY "app"."t" ALTER COLUMN "s" SET DEFAULT nextval('q'::regclass)`,
      'ALTER TABLE ONLY "app"."t" ALTER COLUMN "i" SET NOT NULL',
      'ALTER TABLE ONLY "app"."t" ALTER COLUMN "n" SET NOT NULL',
    ])
  })

  it('declares a local column with its own default and NOT NULL in the CREATE, without altering it afterwards', () => {
    const t = table([col('own', 'int', { default: '1', nullable: false }), col('inh', 'int')])
    const out = pgCreateStatements(ns, t, catalog({ inherits: '"app"."p"', localColumns: new Set(['own']) }))
    expect(out).toEqual(['CREATE TABLE "app"."t" (\n  "own" int NOT NULL DEFAULT 1\n) INHERITS ("app"."p")'])
  })

  it('declares every column when the catalog does not say which are local', () => {
    const t = table([col('a', 'int'), col('b', 'int', { default: '1' })])
    expect(pgCreateStatements(ns, t, catalog({ localColumns: null }))).toEqual([
      'CREATE TABLE "app"."t" (\n  "a" int,\n  "b" int DEFAULT 1\n)',
    ])
  })
})

describe('partitions', () => {
  it('creates each as a partition of its parent with its own indexes, constraints and comment', () => {
    const out = pgCreateStatements(
      ns,
      table([col('a', 'int')]),
      catalog({
        partitionKey: 'RANGE (a)',
        partitions: [
          {
            schema: 's1',
            name: 'p1',
            parentSchema: 'app',
            parent: 't',
            bound: 'FOR VALUES FROM (1) TO (10)',
            partitionKey: 'LIST (a)',
            indexes: ['CREATE INDEX "p1_i" ON ONLY s1.p1 USING btree (a)'],
            constraints: [{ name: 'c1', definition: 'CHECK (a > 0)' }],
            unlogged: true,
            storage: 'fillfactor=50',
            comment: "it's",
          },
          {
            schema: 's1',
            name: 'p2',
            parentSchema: 's1',
            parent: 'p1',
            bound: 'DEFAULT',
            partitionKey: null,
            indexes: [],
            constraints: [],
            unlogged: false,
            storage: null,
            comment: null,
          },
        ],
      })
    )
    expect(out.slice(1)).toEqual([
      'CREATE UNLOGGED TABLE "s1"."p1" PARTITION OF "app"."t" FOR VALUES FROM (1) TO (10) PARTITION BY LIST (a) WITH (fillfactor=50)',
      'CREATE INDEX "p1_i" ON s1.p1 USING btree (a)',
      'ALTER TABLE "s1"."p1" ADD CONSTRAINT "c1" CHECK (a > 0)',
      `COMMENT ON TABLE "s1"."p1" IS 'it''s'`,
      'CREATE TABLE "s1"."p2" PARTITION OF "s1"."p1" DEFAULT',
    ])
  })
})

describe('indexes, constraints and comments', () => {
  const t = (extra: Partial<TableSchema> = {}) => table([col('a', 'int'), col('b', 'int', { comment: "it's" })], extra)

  it("leaves out the primary key index and the ones a constraint creates, and writes the server's own text when it has it", () => {
    const indexes = [
      index('t_pkey', ['a'], { primary: true }),
      index('owned', ['a'], { unique: true }),
      index('own', ['a'], { definition: 'CREATE INDEX own ON app.t USING gin (a)' }),
    ]
    const out = pgCreateStatements(
      ns,
      t({ indexes }),
      catalog({ constraints: [{ name: 'owned', definition: 'UNIQUE (a)', index: 'owned' }] })
    )
    expect(out[1]).toBe('CREATE INDEX own ON app.t USING gin (a)')
    expect(out).toContain('ALTER TABLE "app"."t" ADD CONSTRAINT "owned" UNIQUE (a)')
    expect(out.some((s) => s.includes('t_pkey'))).toBe(false)
    expect(out.filter((s) => s.startsWith('CREATE') && s.includes('INDEX'))).toHaveLength(1)
  })

  it("rebuilds an index without the server's text: unique, partial, a column name quoted and an expression as it is", () => {
    const indexes = [index('i1', ['a', 'lower(b)'], { unique: true, predicate: 'a > 0' }), index('i2', ['b'])]
    const out = pgCreateStatements(ns, t({ indexes }))
    expect(out[1]).toBe('CREATE UNIQUE INDEX "i1" ON "app"."t" ("a", lower(b)) WHERE a > 0')
    expect(out[2]).toBe('CREATE INDEX "i2" ON "app"."t" ("b")')
  })

  it('turns ON ONLY into ON for the index of a partitioned table, so it reaches the partitions', () => {
    const indexes = [index('i', ['a'], { definition: 'CREATE UNIQUE INDEX i ON ONLY app.t USING btree (a)' })]
    expect(pgCreateStatements(ns, t({ indexes }), catalog({ partitionKey: 'RANGE (a)' }))[1]).toBe(
      'CREATE UNIQUE INDEX i ON app.t USING btree (a)'
    )
    expect(pgCreateStatements(ns, t({ indexes }), catalog())[1]).toBe(
      'CREATE UNIQUE INDEX i ON ONLY app.t USING btree (a)'
    )
    const quoted = [index('i', ['a'], { definition: 'CREATE INDEX "my ""i" ON ONLY app.t (a)' })]
    expect(pgCreateStatements(ns, t({ indexes: quoted }), catalog({ partitionKey: 'LIST (a)' }))[1]).toBe(
      'CREATE INDEX "my ""i" ON app.t (a)'
    )
    const other = [index('i', ['a'], { definition: 'CREATE INDEX i ON ONLY_t (a)' })]
    expect(pgCreateStatements(ns, t({ indexes: other }), catalog({ partitionKey: 'LIST (a)' }))[1]).toBe(
      'CREATE INDEX i ON ONLY_t (a)'
    )
  })

  it('adds the constraints the catalog prints, or without it the foreign keys of the description with their actions', () => {
    const fk: ForeignKeyDef = {
      name: 'fk',
      columns: ['a', 'b'],
      refNamespace: { database: 'db', schema: 'other' },
      refTable: 'p',
      refColumns: ['x', 'y'],
      onUpdate: 'CASCADE',
      onDelete: 'SET NULL',
    }
    const bare: ForeignKeyDef = { ...fk, name: 'fk2', onUpdate: null, onDelete: null }
    const described = t({ foreignKeys: [fk, bare] })
    expect(pgCreateStatements(ns, described).slice(1)).toEqual([
      'ALTER TABLE "app"."t" ADD CONSTRAINT "fk" FOREIGN KEY ("a", "b") REFERENCES "other"."p" ("x", "y") ON UPDATE CASCADE ON DELETE SET NULL',
      'ALTER TABLE "app"."t" ADD CONSTRAINT "fk2" FOREIGN KEY ("a", "b") REFERENCES "other"."p" ("x", "y")',
      `COMMENT ON COLUMN "app"."t"."b" IS 'it''s'`,
    ])
    const onlyUpdate = pgCreateStatements(ns, t({ foreignKeys: [{ ...fk, onDelete: null }] }))[1]
    expect(onlyUpdate).toMatch(/\("x", "y"\) ON UPDATE CASCADE$/)
    const onlyDelete = pgCreateStatements(ns, t({ foreignKeys: [{ ...fk, onUpdate: null }] }))[1]
    expect(onlyDelete).toMatch(/\("x", "y"\) ON DELETE SET NULL$/)
    // With the catalog its own text is used, and the description's foreign keys are not written a second time.
    const withCatalog = pgCreateStatements(
      ns,
      described,
      catalog({
        constraints: [{ name: 'c', definition: 'FOREIGN KEY (a) REFERENCES other.p (x) NOT VALID', index: null }],
      })
    )
    expect(withCatalog[1]).toBe(
      'ALTER TABLE "app"."t" ADD CONSTRAINT "c" FOREIGN KEY (a) REFERENCES other.p (x) NOT VALID'
    )
    expect(withCatalog.some((s) => s.includes('"fk"'))).toBe(false)
  })

  it('comments the table and the columns that have a comment, quoting the text', () => {
    const out = pgCreateStatements(ns, t({ comment: "t's" }))
    expect(out).toEqual([out[0], `COMMENT ON TABLE "app"."t" IS 't''s'`, `COMMENT ON COLUMN "app"."t"."b" IS 'it''s'`])
    expect(pgCreateStatements(ns, table([col('a', 'int', { comment: '' })]))[1]).toBe(
      `COMMENT ON COLUMN "app"."t"."a" IS ''`
    )
    expect(pgCreateStatements(ns, table([col('a', 'int')], { comment: '' }))[1]).toBe(
      `COMMENT ON TABLE "app"."t" IS ''`
    )
    expect(pgCreateStatements({ database: 'db' }, table([col('a', 'int')]))[0]).toContain('TABLE "public"."t"')
  })
})

describe('pgTableCatalog: reading what the catalog adds', () => {
  const SEP = String.fromCharCode(31)
  const FIELD = String.fromCharCode(30)
  const script = (over: Partial<Record<'con' | 'rel' | 'local' | 'parts' | 'seq', unknown[][]>> = {}) =>
    scripted([
      [/pg_get_constraintdef\(con\.oid/, rows(over.con ?? [])],
      [/FROM pg_class c WHERE c\.oid = \$1::regclass/, rows(over.rel ?? [['p', null, null, null]])],
      [/a\.attislocal/, rows(over.local ?? [])],
      [/WITH RECURSIVE tree/, rows(over.parts ?? [])],
      [/pg_sequence s ON/, rows(over.seq ?? [])],
    ])

  it('reads a plain table as having nothing extra, and asks about the table by its regclass', async () => {
    const { conn, asked } = script()
    expect(await pgTableCatalog(conn, '"app"."t"')).toEqual({
      constraints: [],
      identityOptions: new Map(),
      inherits: null,
      partitionKey: null,
      partitions: [],
      unlogged: false,
      storage: null,
      localColumns: null,
    })
    expect(asked).toHaveLength(3)
    for (const q of asked) expect(q.params).toEqual(['"app"."t"'])
  })

  it('reads the constraints with the index each owns, and the table options', async () => {
    const { conn } = script({
      con: [
        ['uq', 'UNIQUE (a)', 'uq_idx'],
        ['ck', 'CHECK (a > 0)', null],
        ['nl', null, undefined],
      ],
      rel: [['u', "fillfactor='70'", 'RANGE (a)', '"app"."p"']],
    })
    const cat = await pgTableCatalog(conn, 't')
    expect(cat.constraints).toEqual([
      { name: 'uq', definition: 'UNIQUE (a)', index: 'uq_idx' },
      { name: 'ck', definition: 'CHECK (a > 0)', index: null },
      { name: 'nl', definition: '', index: null },
    ])
    expect(cat.unlogged).toBe(true)
    expect(cat.storage).toBe("fillfactor='70'")
    expect(cat.partitionKey).toBe('RANGE (a)')
    expect(cat.inherits).toBe('"app"."p"')
  })

  it('reads an empty storage, key or parent list as none, and any persistence but u as logged', async () => {
    const { conn } = script({ rel: [['t', '', '', '']] })
    const cat = await pgTableCatalog(conn, 't')
    expect([cat.unlogged, cat.storage, cat.partitionKey, cat.inherits]).toEqual([false, null, null, null])
    const none = script({ rel: [] })
    expect((await pgTableCatalog(none.conn, 't')).unlogged).toBe(false)
  })

  it('asks for the local columns only of an inheritance child', async () => {
    const child = script({ rel: [['p', null, null, '"p"']], local: [['own'], ['own2']] })
    const cat = await pgTableCatalog(child.conn, 't')
    expect(cat.localColumns).toEqual(new Set(['own', 'own2']))
    expect(child.asked.some((q) => /attislocal/.test(q.text))).toBe(true)
    expect(child.asked.find((q) => /attislocal/.test(q.text))?.params).toEqual(['t'])
    const plain = script()
    await pgTableCatalog(plain.conn, 't')
    expect(plain.asked.some((q) => /attislocal/.test(q.text))).toBe(false)
  })

  it('reads the partitions of a partitioned table, splitting its indexes and constraints at the separators', async () => {
    const { conn, asked } = script({
      rel: [['p', null, 'RANGE (a)', null]],
      parts: [
        [
          'p1',
          't',
          'FOR VALUES FROM (1) TO (2)',
          'LIST (b)',
          's1',
          'app',
          'u',
          'fillfactor=50',
          'a comment',
          `CREATE INDEX i1 ON p1 (a)${SEP}CREATE INDEX i2 ON p1 (b)`,
          `c1${FIELD}CHECK (a > 0)${SEP}c2${FIELD}UNIQUE (b)`,
        ],
        ['p2', 'p1', 'DEFAULT', '', 's1', 's1', 'p', null, '', '', ''],
      ],
    })
    const cat = await pgTableCatalog(conn, 't')
    expect(cat.partitions).toEqual([
      {
        name: 'p1',
        parent: 't',
        bound: 'FOR VALUES FROM (1) TO (2)',
        partitionKey: 'LIST (b)',
        schema: 's1',
        parentSchema: 'app',
        unlogged: true,
        storage: 'fillfactor=50',
        comment: 'a comment',
        indexes: ['CREATE INDEX i1 ON p1 (a)', 'CREATE INDEX i2 ON p1 (b)'],
        constraints: [
          { name: 'c1', definition: 'CHECK (a > 0)' },
          { name: 'c2', definition: 'UNIQUE (b)' },
        ],
      },
      {
        name: 'p2',
        parent: 'p1',
        bound: 'DEFAULT',
        partitionKey: null,
        schema: 's1',
        parentSchema: 's1',
        unlogged: false,
        storage: null,
        comment: null,
        indexes: [],
        constraints: [],
      },
    ])
    expect(asked.find((q) => /WITH RECURSIVE/.test(q.text))?.params).toEqual(['t', SEP, FIELD])
  })

  it('writes the identity sequence options that differ from the defaults, in a fixed order', async () => {
    const { conn } = script({
      seq: [
        ['a', 1000, 1, 1, '9223372036854775807', 10, false],
        ['b', 1, 2, 5, '100', 1, true],
        ['c', 1, 1, 1, '2147483647', 1, false],
        ['d', 1, 1, 1, '32767', 1, false],
        ['e', 1, 1, 1, '9223372036854775807', 1, null],
        ['f', 1, 1, 1, '', 1, false],
      ],
    })
    const { identityOptions } = await pgTableCatalog(conn, 't')
    expect(identityOptions.get('a')).toBe('START WITH 1000 CACHE 10')
    expect(identityOptions.get('b')).toBe('INCREMENT BY 2 MINVALUE 5 MAXVALUE 100 CYCLE')
    expect([...identityOptions.keys()]).toEqual(['a', 'b'])
  })
})
