import type { ColumnSpec, DdlOp, Namespace, TableSchema } from '@tsmyadmin/shared'
import { type Conn, firstResult } from '../base.ts'
import { addForeignKeySql, createIndexSql } from '../sql/ddl-common.ts'
import { pgAdvanceSequence } from '../sql/export.ts'
import { pgLiteral } from '../sql/literal.ts'
import { quoteIdent, quoteTable } from '../sql/quote.ts'
import { AdapterError, type DdlBuilder } from '../types.ts'

const id = (s: string) => quoteIdent('postgres', s)

function defaultSql(c: ColumnSpec): string | null {
  if (!c.default) return null
  return c.default.kind === 'literal' ? pgLiteral(c.default.value) : c.default.sql
}

function columnDef(c: ColumnSpec): string {
  const parts = [id(c.name), c.dataType]
  if (c.autoIncrement) parts.push('GENERATED BY DEFAULT AS IDENTITY')
  if (!c.nullable) parts.push('NOT NULL')
  const def = defaultSql(c)
  if (def) parts.push(`DEFAULT ${def}`)
  return parts.join(' ')
}

function commentSql(t: string, c: ColumnSpec): string[] {
  return c.comment === null ? [] : [`COMMENT ON COLUMN ${t}.${id(c.name)} IS ${pgLiteral(c.comment)}`]
}

export const pgDdl: DdlBuilder = {
  build(ns: Namespace, op: DdlOp): string[] {
    // Database-level ops have no table; handle them before touching op.table.
    switch (op.op) {
      case 'createDatabase':
        return [`CREATE DATABASE ${id(op.name)}`]
      case 'createSchema':
        return [`CREATE SCHEMA ${id(op.name)}`]
      case 'dropDatabase':
        // FORCE (PostgreSQL 13+): other sessions — including this tool's own idle pooled connections to the
        // database just browsed — would otherwise make the DROP wait and fail with "being accessed by other users".
        return [`DROP DATABASE ${id(op.name)} WITH (FORCE)`]
      case 'enableEvent':
      case 'disableEvent':
      case 'dropEvent':
        throw new AdapterError('UNSUPPORTED', 'PostgreSQL has no event scheduler')
      case 'dropTables':
        return [`DROP TABLE ${op.tables.map((x) => quoteTable('postgres', ns, x)).join(', ')}`]
      case 'truncateTables':
        return [`TRUNCATE TABLE ${op.tables.map((x) => quoteTable('postgres', ns, x)).join(', ')}`]
      default:
        break
    }
    const t = quoteTable('postgres', ns, op.table)
    const schema = id(ns.schema ?? 'public')
    switch (op.op) {
      case 'createTable': {
        const defs = op.columns.map(columnDef)
        if (op.primaryKey.length > 0) defs.push(`PRIMARY KEY (${op.primaryKey.map(id).join(', ')})`)
        return [`CREATE TABLE ${t} (\n  ${defs.join(',\n  ')}\n)`, ...op.columns.flatMap((c) => commentSql(t, c))]
      }
      case 'addColumn':
        // PostgreSQL cannot position columns; `after` is ignored.
        return [`ALTER TABLE ${t} ADD COLUMN ${columnDef(op.column)}`, ...commentSql(t, op.column)]
      case 'modifyColumn': {
        const c = op.column
        const prev = op.previous
        const out: string[] = []
        if (op.name !== c.name) out.push(`ALTER TABLE ${t} RENAME COLUMN ${id(op.name)} TO ${id(c.name)}`)
        const col = id(c.name)
        // With the current definition known, only what changed is emitted: an ALTER TYPE rewrites the table
        // and a DROP DEFAULT the user never asked for is exactly what a reviewing DBA refuses to run.
        if (prev === undefined || prev.dataType !== c.dataType) {
          out.push(`ALTER TABLE ${t} ALTER COLUMN ${col} TYPE ${c.dataType}`)
        }
        if (prev === undefined || prev.nullable !== c.nullable) {
          out.push(`ALTER TABLE ${t} ALTER COLUMN ${col} ${c.nullable ? 'DROP NOT NULL' : 'SET NOT NULL'}`)
        }
        // A serial / identity column keeps its generator: touching DEFAULT would drop nextval() or fail on an
        // identity column. Turning a plain column into an identity one is left to hand-written SQL.
        if (!c.autoIncrement && (prev === undefined || defaultSql(prev) !== defaultSql(c))) {
          const def = defaultSql(c)
          out.push(`ALTER TABLE ${t} ALTER COLUMN ${col} ${def ? `SET DEFAULT ${def}` : 'DROP DEFAULT'}`)
        }
        if (c.comment !== null && (prev === undefined || prev.comment !== c.comment)) {
          out.push(`COMMENT ON COLUMN ${t}.${col} IS ${pgLiteral(c.comment)}`)
        } else if (c.comment === null && prev?.comment != null) {
          out.push(`COMMENT ON COLUMN ${t}.${col} IS NULL`)
        }
        return out
      }
      case 'dropColumn':
        return [`ALTER TABLE ${t} DROP COLUMN ${id(op.name)}`]
      case 'addIndex':
        return [createIndexSql('postgres', ns, op)]
      case 'dropIndex':
        return [`DROP INDEX ${schema}.${id(op.name)}`]
      case 'addForeignKey':
        return [addForeignKeySql('postgres', ns, op)]
      case 'dropForeignKey':
        return [`ALTER TABLE ${t} DROP CONSTRAINT ${id(op.name)}`]
      case 'dropTable':
        return [
          `DROP ${op.kind === 'materialized_view' ? 'MATERIALIZED VIEW' : op.kind === 'view' ? 'VIEW' : 'TABLE'} ${t}`,
        ]
      case 'truncateTable':
        return [`TRUNCATE TABLE ${t}`]
      case 'renameTable':
        // Renaming keeps the table in its schema; the new name must not be qualified.
        return [`ALTER TABLE ${t} RENAME TO ${id(op.newName)}`]
      case 'setTableOptions':
        if (op.engine !== undefined || op.collation !== undefined || op.autoIncrement !== undefined) {
          throw new AdapterError('UNSUPPORTED', 'PostgreSQL tables have no engine, collation or AUTO_INCREMENT option')
        }
        if (op.comment === undefined) throw new AdapterError('VALIDATION', 'No table option to change')
        return [`COMMENT ON TABLE ${t} IS ${op.comment === null ? 'NULL' : pgLiteral(op.comment)}`]
      case 'maintainTable':
        switch (op.action) {
          case 'analyze':
            return [`ANALYZE ${t}`]
          case 'vacuum':
            return [`VACUUM (ANALYZE) ${t}`]
          case 'optimize':
            return [`VACUUM (FULL, ANALYZE) ${t}`]
          case 'check':
            throw new AdapterError('UNSUPPORTED', 'PostgreSQL has no CHECK TABLE')
        }
        break
      case 'copyTable': {
        const target = quoteTable('postgres', ns, op.newName)
        // INCLUDING ALL keeps defaults, constraints (incl. PK), indexes and comments; foreign keys are not copied.
        const out = [`CREATE TABLE ${target} (LIKE ${t} INCLUDING ALL)`]
        if (op.withData) {
          // OVERRIDING SYSTEM VALUE keeps GENERATED ALWAYS AS IDENTITY values; generated columns are left out by the caller.
          const cols = op.columns?.map(id).join(', ')
          out.push(
            cols
              ? `INSERT INTO ${target} (${cols}) OVERRIDING SYSTEM VALUE SELECT ${cols} FROM ${t}`
              : `INSERT INTO ${target} OVERRIDING SYSTEM VALUE SELECT * FROM ${t}`
          )
        }
        // LIKE copies a serial column's DEFAULT nextval('<source>_seq'): the copy would draw ids from the
        // source's sequence and pin it (DROP TABLE source then fails). Give the copy its own sequence, as
        // MySQL's CREATE TABLE ... LIKE gives it its own AUTO_INCREMENT.
        for (const c of op.serialColumns ?? []) {
          const seq = quoteTable('postgres', ns, `${op.newName}_${c}_seq`)
          out.push(
            `CREATE SEQUENCE ${seq} OWNED BY ${target}.${id(c)}`,
            `ALTER TABLE ${target} ALTER COLUMN ${id(c)} SET DEFAULT nextval(${pgLiteral(seq)}::regclass)`
          )
        }
        if (op.withData) {
          // INCLUDING IDENTITY gives the copy fresh sequences starting at their minimum: advance them past the
          // copied ids, exactly as the SQL dump does, or the first insert into the copy collides.
          for (const c of [...(op.identityColumns ?? []), ...(op.serialColumns ?? [])]) {
            out.push(pgAdvanceSequence(target, c))
          }
        }
        return out
      }
    }
  },
}

/** Index entries are real column names (from pg_attribute, unquoted) or expressions (from pg_get_indexdef). */
const indexCol = (columns: Set<string>) => (c: string) => (columns.has(c) ? id(c) : c)

/** What TableSchema does not carry but a faithful CREATE needs; read by `pgTableCatalog` in a few extra round trips. */
export interface PgTableCatalog {
  /**
   * The table's own (not inherited) CHECK / UNIQUE / EXCLUDE / FOREIGN KEY constraints as `pg_get_constraintdef`
   * prints them (MATCH, actions, DEFERRABLE, NOT VALID included), with the index each one owns.
   */
  constraints: { name: string; definition: string; index: string | null }[]
  /** Identity sequence options per column, already rendered (`START WITH 1000 CACHE 10`). */
  identityOptions: Map<string, string>
  /** Parents of an inheritance child (`INHERITS (…)`). */
  inherits: string[]
  /** `PARTITION BY …` of a partitioned table. */
  partitionKey: string | null
  /** Partitions (all levels, parents first): created as `PARTITION OF` right after the table. */
  partitions: { name: string; parent: string; bound: string; partitionKey: string | null }[]
  unlogged: boolean
  /** Storage parameters (`fillfactor=70`, `autovacuum_enabled=false`). */
  storage: string[]
}

/** Type bounds an ascending identity sequence takes by default: MAXVALUE is only printed when it differs. */
const IDENTITY_MAX = new Set(['32767', '2147483647', '9223372036854775807'])

export async function pgTableCatalog(conn: Conn, regclass: string): Promise<PgTableCatalog> {
  const con = firstResult(
    await conn.query(
      `SELECT con.conname, pg_get_constraintdef(con.oid, true), ic.relname
       FROM pg_constraint con LEFT JOIN pg_class ic ON ic.oid = con.conindid AND con.contype IN ('u', 'x')
       WHERE con.conrelid = $1::regclass AND con.contype IN ('c', 'u', 'x', 'f') AND con.conislocal
       ORDER BY con.contype, con.conname`,
      [regclass]
    )
  )
  const out: PgTableCatalog = {
    constraints: [],
    identityOptions: new Map(),
    inherits: [],
    partitionKey: null,
    partitions: [],
    unlogged: false,
    storage: [],
  }
  for (const row of con.rows) {
    const index = row[2]
    out.constraints.push({
      name: String(row[0] ?? ''),
      definition: String(row[1] ?? ''),
      index: typeof index === 'string' ? index : null,
    })
  }
  const rel = firstResult(
    await conn.query(
      `SELECT c.relpersistence, c.reloptions, pg_get_partkeydef(c.oid),
              (SELECT string_agg(quote_ident(pn.nspname) || '.' || quote_ident(p.relname), ', ' ORDER BY i.inhseqno)
                 FROM pg_inherits i JOIN pg_class p ON p.oid = i.inhparent JOIN pg_namespace pn ON pn.oid = p.relnamespace
                 WHERE i.inhrelid = c.oid AND NOT c.relispartition)
       FROM pg_class c WHERE c.oid = $1::regclass`,
      [regclass]
    )
  )
  const relRow = rel.rows[0]
  out.unlogged = String(relRow?.[0]) === 'u'
  out.storage = String(relRow?.[1] ?? '')
    .replace(/^\{|\}$/g, '')
    .split(',')
    .map((o) => o.trim())
    .filter((o) => o.length > 0)
  const partKey = relRow?.[2]
  out.partitionKey = typeof partKey === 'string' && partKey.length > 0 ? partKey : null
  const parents = relRow?.[3]
  if (typeof parents === 'string' && parents.length > 0) out.inherits = [parents]
  if (out.partitionKey) {
    // Every partition below this table, parents before their sub-partitions.
    const parts = firstResult(
      await conn.query(
        `WITH RECURSIVE tree AS (
           SELECT i.inhrelid, i.inhparent, 1 AS depth FROM pg_inherits i WHERE i.inhparent = $1::regclass
           UNION ALL
           SELECT i.inhrelid, i.inhparent, t.depth + 1 FROM pg_inherits i JOIN tree t ON i.inhparent = t.inhrelid
         )
         SELECT c.relname, p.relname, pg_get_expr(c.relpartbound, c.oid), pg_get_partkeydef(c.oid)
         FROM tree JOIN pg_class c ON c.oid = tree.inhrelid JOIN pg_class p ON p.oid = tree.inhparent
         WHERE c.relispartition ORDER BY tree.depth, c.relname`,
        [regclass]
      )
    )
    out.partitions = parts.rows.map((row) => {
      const key = row[3]
      return {
        name: String(row[0] ?? ''),
        parent: String(row[1] ?? ''),
        bound: String(row[2] ?? ''),
        partitionKey: typeof key === 'string' && key.length > 0 ? key : null,
      }
    })
  }
  const seq = firstResult(
    await conn.query(
      `SELECT a.attname, s.seqstart, s.seqincrement, s.seqmin, s.seqmax, s.seqcache, s.seqcycle
       FROM pg_attribute a
       JOIN pg_depend d ON d.refobjid = a.attrelid AND d.refobjsubid = a.attnum AND d.deptype = 'i' AND d.classid = 'pg_class'::regclass
       JOIN pg_sequence s ON s.seqrelid = d.objid
       WHERE a.attrelid = $1::regclass AND a.attidentity <> ''`,
      [regclass]
    )
  )
  for (const row of seq.rows) {
    const [start, inc, min, max, cache] = [row[1], row[2], row[3], row[4], row[5]].map((v) => String(v ?? ''))
    const parts = [
      start !== '1' ? `START WITH ${start}` : '',
      inc !== '1' ? `INCREMENT BY ${inc}` : '',
      min !== '1' ? `MINVALUE ${min}` : '',
      max && !IDENTITY_MAX.has(max) ? `MAXVALUE ${max}` : '',
      cache !== '1' ? `CACHE ${cache}` : '',
      row[6] === true ? 'CYCLE' : '',
    ].filter((p) => p.length > 0)
    if (parts.length > 0) out.identityOptions.set(String(row[0] ?? ''), parts.join(' '))
  }
  return out
}

/**
 * Reconstructs CREATE TABLE + indexes + constraints + foreign keys + comments from catalog metadata (see
 * PostgresAdapter.showCreateTable). Without `catalog` (DDL previews) constraints and identity options are omitted.
 */
export function pgCreateStatements(ns: Namespace, schema: TableSchema, catalog?: PgTableCatalog): string[] {
  const t = quoteTable('postgres', ns, schema.name)
  const defs = schema.columns.map((c) => {
    const identity = c.extra.startsWith('identity') || c.extra === 'serial'
    const generated = c.extra === 'generated stored'
    const parts = [id(c.name), c.dataType]
    // A non-default collation is part of the type (ordering and index semantics change without it).
    if (c.collation !== null) parts.push(`COLLATE ${id(c.collation)}`)
    if (identity) {
      const options = catalog?.identityOptions.get(c.name)
      parts.push(c.extra === 'identity always' ? 'GENERATED ALWAYS AS IDENTITY' : 'GENERATED BY DEFAULT AS IDENTITY')
      if (options) parts.push(`(${options})`)
    }
    // describeTable stores the generation expression in `default`; it is not a DEFAULT (it may reference siblings).
    if (generated && c.default !== null) parts.push(`GENERATED ALWAYS AS (${c.default}) STORED`)
    if (!c.nullable) parts.push('NOT NULL')
    if (c.default !== null && !identity && !generated) parts.push(`DEFAULT ${c.default}`)
    return parts.join(' ')
  })
  if (schema.primaryKey.length > 0) defs.push(`PRIMARY KEY (${schema.primaryKey.map(id).join(', ')})`)
  const inherits = catalog && catalog.inherits.length > 0 ? ` INHERITS (${catalog.inherits.join(', ')})` : ''
  const partitionBy = catalog?.partitionKey ? ` PARTITION BY ${catalog.partitionKey}` : ''
  const storage = catalog && catalog.storage.length > 0 ? ` WITH (${catalog.storage.join(', ')})` : ''
  const out = [
    `CREATE ${catalog?.unlogged ? 'UNLOGGED ' : ''}TABLE ${t} (\n  ${defs.join(',\n  ')}\n)${inherits}${partitionBy}${storage}`,
  ]
  // Partitions carry no columns of their own; sub-partitions come after their parent.
  for (const p of catalog?.partitions ?? []) {
    // relpartbound prints as `FOR VALUES …` or `DEFAULT`.
    out.push(
      `CREATE TABLE ${quoteTable('postgres', ns, p.name)} PARTITION OF ${quoteTable('postgres', ns, p.parent)} ${p.bound}${p.partitionKey ? ` PARTITION BY ${p.partitionKey}` : ''}`
    )
  }
  const names = new Set(schema.columns.map((c) => c.name))
  // An index owned by a UNIQUE / EXCLUDE constraint is created by the constraint, not on its own.
  const owned = new Set(catalog?.constraints.map((c) => c.index).filter((i): i is string => i !== null))
  for (const i of schema.indexes) {
    if (i.primary || owned.has(i.name)) continue
    // The server's own statement keeps access method, direction, opclass and INCLUDE; reconstruct only without it.
    if (i.definition) {
      out.push(i.definition)
      continue
    }
    const where = i.predicate ? ` WHERE ${i.predicate}` : ''
    out.push(
      `CREATE ${i.unique ? 'UNIQUE ' : ''}INDEX ${id(i.name)} ON ${t} (${i.columns.map(indexCol(names)).join(', ')})${where}`
    )
  }
  if (catalog) {
    // The server's own text keeps MATCH, action column lists, DEFERRABLE and NOT VALID.
    for (const c of catalog.constraints) out.push(`ALTER TABLE ${t} ADD CONSTRAINT ${id(c.name)} ${c.definition}`)
  } else {
    for (const fk of schema.foreignKeys) {
      const ref = quoteTable('postgres', fk.refNamespace, fk.refTable)
      const actions = [
        fk.onUpdate ? ` ON UPDATE ${fk.onUpdate}` : '',
        fk.onDelete ? ` ON DELETE ${fk.onDelete}` : '',
      ].join('')
      out.push(
        `ALTER TABLE ${t} ADD CONSTRAINT ${id(fk.name)} FOREIGN KEY (${fk.columns.map(id).join(', ')}) REFERENCES ${ref} (${fk.refColumns.map(id).join(', ')})${actions}`
      )
    }
  }
  if (schema.comment !== null) out.push(`COMMENT ON TABLE ${t} IS ${pgLiteral(schema.comment)}`)
  for (const c of schema.columns)
    if (c.comment !== null) out.push(`COMMENT ON COLUMN ${t}.${id(c.name)} IS ${pgLiteral(c.comment)}`)
  return out
}
