import type { ColumnSpec, DdlOp, Namespace } from '@tsmyadmin/shared'
import {
  addForeignKeySql,
  columnKeySql,
  createIndexSql,
  dropOrder,
  moveRepeatingGroupSql,
  splitTableSql,
} from '../sql/ddl-common.ts'
import { pgLiteral } from '../sql/literal.ts'
import { quoteIdent, quoteTable } from '../sql/quote.ts'
import { AdapterError, type DdlBuilder } from '../types.ts'
import { pgAdvanceSequence } from './export.ts'

const id = (s: string) => quoteIdent('postgres', s)
const PG_DROP_KEYWORD = {
  table: 'TABLE',
  view: 'VIEW',
  materialized_view: 'MATERIALIZED VIEW',
  sequence: 'SEQUENCE',
} as const

/**
 * Ends this tool's **idle** connections to a database under the account that signed in (`session_user`, which a
 * role's default `SET ROLE` does not change — `current_user` would then match none of them).
 *
 * Idle, because application name and account do not single out this person: two people sharing one database
 * account both show up as `tsmyadmin` / that user. A pooled connection waiting for its next query is idle; someone
 * else's running export is not, and is left alone — PostgreSQL then refuses the rename, which is the right outcome.
 *
 * With a timeout (PostgreSQL 14+): the plain call only signals the backend and returns, so the ALTER right after it
 * could still find the connection there and fail with "being accessed by other users".
 */
function releaseOwnConnections(database: string): string {
  return `SELECT pg_terminate_backend(pid, 5000) FROM pg_stat_activity WHERE datname = ${pgLiteral(database)} AND application_name = 'tsmyadmin' AND usename = session_user AND state = 'idle' AND pid <> pg_backend_pid()`
}

function defaultSql(c: ColumnSpec): string | null {
  if (!c.default) return null
  return c.default.kind === 'literal' ? pgLiteral(c.default.value) : c.default.sql
}

function columnDef(c: ColumnSpec): string {
  const parts = [id(c.name), c.dataType]
  if (c.collation) parts.push(`COLLATE ${id(c.collation)}`)
  if (c.generated) {
    // Computed by the server: no default or identity of its own. VIRTUAL needs PostgreSQL 18.
    parts.push(`GENERATED ALWAYS AS (${c.generated.expression}) ${c.generated.stored ? 'STORED' : 'VIRTUAL'}`)
    if (!c.nullable) parts.push('NOT NULL')
    return parts.join(' ')
  }
  if (c.autoIncrement) parts.push('GENERATED BY DEFAULT AS IDENTITY')
  if (!c.nullable) parts.push('NOT NULL')
  const def = defaultSql(c)
  if (def) parts.push(`DEFAULT ${def}`)
  return parts.join(' ')
}

/**
 * What changing a column's generation takes: a new expression (PostgreSQL 17), or dropping it to keep the values
 * as an ordinary column. Making an existing column generated, or switching STORED / VIRTUAL, is not something
 * PostgreSQL can do in place.
 */
function generatedChange(
  t: string,
  col: string,
  /** undefined when the current definition is not known: the expression is then written as given. */
  before: ColumnSpec['generated'] | undefined,
  after: ColumnSpec['generated']
): string[] {
  if (before === undefined)
    return after ? [`ALTER TABLE ${t} ALTER COLUMN ${col} SET EXPRESSION AS (${after.expression})`] : []
  if (!before && !after) return []
  if (before && !after) return [`ALTER TABLE ${t} ALTER COLUMN ${col} DROP EXPRESSION`]
  if (!before || !after || before.stored !== after.stored) {
    throw new AdapterError(
      'UNSUPPORTED',
      'PostgreSQL cannot make an existing column generated, or change how it is kept'
    )
  }
  if (before.expression === after.expression) return []
  return [`ALTER TABLE ${t} ALTER COLUMN ${col} SET EXPRESSION AS (${after.expression})`]
}

function commentSql(t: string, c: ColumnSpec): string[] {
  return c.comment === null ? [] : [`COMMENT ON COLUMN ${t}.${id(c.name)} IS ${pgLiteral(c.comment)}`]
}

/**
 * Code as a dollar-quoted string, under a tag the code itself does not contain — so nothing in it needs
 * escaping, and nothing in it can end the string early.
 */
function dollarQuoted(code: string): string {
  let tag = 'body'
  for (let n = 1; code.includes(`$${tag}$`); n++) tag = `body${n}`
  return `$${tag}$\n${code.trim()}\n$${tag}$`
}

/** PostgreSQL has no DEFINER clause or MySQL-style characteristics: say so instead of dropping them silently. */
function onlyMysql(what: string, present: unknown): void {
  if (present !== undefined)
    throw new AdapterError('UNSUPPORTED', `${what} is a MySQL option; PostgreSQL has no equivalent`)
}

/** A parameter list with the modes and spacing the catalog may or may not print, for comparing two of them. */
const normalizedParams = (list: string) =>
  list
    .split(',')
    .map((p) =>
      p
        .trim()
        .replace(/^in\s+/i, '')
        .replace(/\s+/g, ' ')
        .toLowerCase()
    )
    .filter((p) => p !== '')
    .join(',')

/** The trigger function a PostgreSQL trigger runs, created next to it and named after it. */
function triggerFunction(ns: Namespace, op: Extract<DdlOp, { op: 'createTrigger' }>, orReplace: boolean): string {
  const fn = quoteTable('postgres', ns, `${op.name}_fn`)
  return `CREATE ${orReplace ? 'OR REPLACE ' : ''}FUNCTION ${fn}() RETURNS trigger LANGUAGE plpgsql AS ${dollarQuoted(op.body)}`
}

function createRoutineSql(ns: Namespace, op: Extract<DdlOp, { op: 'createRoutine' }>, orReplace = false): string[] {
  onlyMysql('DEFINER', op.definer)
  onlyMysql('A data-access characteristic', op.dataAccess)
  const kind = op.kind === 'function' ? 'FUNCTION' : 'PROCEDURE'
  const signature = `${quoteTable('postgres', ns, op.name)}(${op.params
    .map((p) => `${p.mode} ${id(p.name)} ${p.type}`)
    .join(', ')})`
  if (op.kind === 'function' && !op.returns) throw new AdapterError('UNSUPPORTED', 'A function needs a return type')
  const returns = op.kind === 'function' ? ` RETURNS ${op.returns}` : ''
  // The language is schema-validated as an identifier, hence safe unquoted.
  const security = op.sqlSecurity ? ` SECURITY ${op.sqlSecurity}` : ''
  const create = `CREATE ${orReplace ? 'OR REPLACE ' : ''}${kind} ${signature}${returns} LANGUAGE ${op.language}${op.deterministic ? ' IMMUTABLE' : ''}${security} AS ${dollarQuoted(op.body)}`
  return op.comment ? [create, `COMMENT ON ${kind} ${signature} IS ${pgLiteral(op.comment)}`] : [create]
}

/**
 * Statements that must land together, in one transaction (PostgreSQL's DDL is transactional). The SQL console runs
 * a script on one connection, stops at the first error and rolls back what is open, so a CREATE INDEX that fails
 * on duplicates leaves the dropped index in place instead of gone.
 */
function inTransaction(statements: string[]): string[] {
  return statements.length > 1 ? ['BEGIN', ...statements, 'COMMIT'] : statements
}

export const pgDdl: DdlBuilder = {
  build(ns: Namespace, op: DdlOp): string[] {
    // Database-level ops have no table; handle them before touching op.table.
    switch (op.op) {
      case 'createDatabase':
        // A collation other than the template's needs template0, which has no connections to conflict with it.
        return [
          op.collation
            ? `CREATE DATABASE ${id(op.name)} TEMPLATE template0 LC_COLLATE ${pgLiteral(op.collation)} LC_CTYPE ${pgLiteral(op.collation)}`
            : `CREATE DATABASE ${id(op.name)}`,
        ]
      case 'createSchema':
        return [`CREATE SCHEMA ${id(op.name)}`]
      case 'setServerVariable':
        return [
          op.value === undefined
            ? `ALTER SYSTEM RESET ${op.name}`
            : `ALTER SYSTEM SET ${op.name} = ${pgLiteral(op.value)}`,
          'SELECT pg_reload_conf()',
        ]
      case 'dropDatabases':
        return op.names.map((name) => `DROP DATABASE ${id(name)} WITH (FORCE)`)
      case 'dropDatabase':
        // FORCE (PostgreSQL 13+): other sessions — including this tool's own idle pooled connections to the
        // database just browsed — would otherwise make the DROP wait and fail with "being accessed by other users".
        return [`DROP DATABASE ${id(op.name)} WITH (FORCE)`]
      // Both need the source database to have no other sessions. Only this tool's idle pooled connections are
      // ended — its pool keeps some to a database that was just browsed. Anything else still connected makes
      // PostgreSQL refuse, which is the right outcome rather than something to force past.
      case 'renameDatabase':
        return [releaseOwnConnections(op.name), `ALTER DATABASE ${id(op.name)} RENAME TO ${id(op.newName)}`]
      case 'copyDatabase':
        if (!op.withData || op.structure === false)
          throw new AdapterError('UNSUPPORTED', 'PostgreSQL copies a database with its structure and its data')
        return [releaseOwnConnections(op.name), `CREATE DATABASE ${id(op.newName)} TEMPLATE ${id(op.name)}`]
      case 'replaceInColumn': {
        const c = id(op.column)
        const replaced = op.regex
          ? `regexp_replace(${c}, ${pgLiteral(op.find)}, ${pgLiteral(op.replace)}, 'g')`
          : `replace(${c}, ${pgLiteral(op.find)}, ${pgLiteral(op.replace)})`
        return [
          `UPDATE ${quoteTable('postgres', ns, op.table)} SET ${c} = ${replaced} WHERE ${replaced} IS DISTINCT FROM ${c}`,
        ]
      }
      case 'splitTable':
        return splitTableSql('postgres', ns, op)
      case 'moveRepeatingGroup':
        return moveRepeatingGroupSql('postgres', ns, op)
      case 'moveTable':
        return [`ALTER TABLE ${quoteTable('postgres', ns, op.table)} SET SCHEMA ${id(op.to)}`]
      case 'createView': {
        onlyMysql('ALGORITHM', op.algorithm)
        onlyMysql('DEFINER', op.definer)
        onlyMysql('SQL SECURITY', op.sqlSecurity)
        const cols = op.columns && op.columns.length > 0 ? ` (${op.columns.map(id).join(', ')})` : ''
        const check = op.checkOption ? `\nWITH ${op.checkOption} CHECK OPTION` : ''
        return [
          `CREATE ${op.orReplace ? 'OR REPLACE ' : ''}VIEW ${quoteTable('postgres', ns, op.name)}${cols} AS ${op.select.trim().replace(/[\s;]+$/, '')}${check}`,
        ]
      }
      case 'dropRoutine':
        // A PostgreSQL routine is known by its parameter list: two may share a name.
        return [
          `DROP ${op.kind === 'function' ? 'FUNCTION' : 'PROCEDURE'} ${quoteTable('postgres', ns, op.name)}(${op.parameters ?? ''})`,
        ]
      case 'alterRoutine': {
        onlyMysql('A data-access characteristic', op.dataAccess)
        const kind = op.kind === 'function' ? 'FUNCTION' : 'PROCEDURE'
        const signature = `${quoteTable('postgres', ns, op.name)}(${op.parameters ?? ''})`
        const out = [
          ...(op.sqlSecurity ? [`ALTER ${kind} ${signature} SECURITY ${op.sqlSecurity}`] : []),
          ...(op.comment !== undefined
            ? [`COMMENT ON ${kind} ${signature} IS ${op.comment === '' ? 'NULL' : pgLiteral(op.comment)}`]
            : []),
        ]
        if (out.length === 0) throw new AdapterError('VALIDATION', 'No routine characteristic to change')
        return inTransaction(out)
      }
      case 'dropTrigger':
        return [`DROP TRIGGER ${id(op.name)} ON ${quoteTable('postgres', ns, op.table)}`]
      case 'createRoutine':
        return createRoutineSql(ns, op)
      case 'replaceRoutine': {
        const { replaces, op: _replace, ...rest } = op
        const create = { op: 'createRoutine' as const, ...rest }
        const params = create.params.map((p) => `${p.mode} ${id(p.name)} ${p.type}`).join(', ')
        // The same name and parameters: replaced in place, which keeps the privileges. Otherwise the old overload is
        // dropped and this created, in one transaction so a refused definition leaves the old one as it was.
        const inPlace =
          replaces.kind === create.kind &&
          replaces.name === create.name &&
          normalizedParams(replaces.parameters ?? '') === normalizedParams(params.replaceAll('"', ''))
        return inPlace
          ? inTransaction(createRoutineSql(ns, create, true))
          : inTransaction([
              ...pgDdl.build(ns, {
                op: 'dropRoutine',
                kind: replaces.kind,
                name: replaces.name,
                ...(replaces.parameters !== undefined ? { parameters: replaces.parameters } : {}),
              }),
              ...createRoutineSql(ns, create),
            ])
      }
      case 'replaceTrigger': {
        onlyMysql('DEFINER', op.definer)
        const { replaces, op: _replace, ...rest } = op
        const create = { op: 'createTrigger' as const, ...rest }
        return inTransaction([
          ...pgDdl.build(ns, { op: 'dropTrigger', name: replaces.name, table: replaces.table }),
          // A renamed trigger leaves its old function behind; one shared with another trigger stays (and refuses).
          ...(replaces.name !== create.name
            ? [`DROP FUNCTION IF EXISTS ${quoteTable('postgres', ns, `${replaces.name}_fn`)}()`]
            : []),
          triggerFunction(ns, create, true),
          `CREATE TRIGGER ${id(create.name)} ${create.timing} ${create.event} ON ${quoteTable('postgres', ns, create.table)} FOR EACH ROW EXECUTE FUNCTION ${quoteTable('postgres', ns, `${create.name}_fn`)}()`,
        ])
      }
      case 'replaceEvent':
        throw new AdapterError('UNSUPPORTED', 'PostgreSQL has no event scheduler')
      case 'createTrigger': {
        onlyMysql('DEFINER', op.definer)
        // PostgreSQL runs a trigger function; it is created next to the trigger and named after it.
        const fn = quoteTable('postgres', ns, `${op.name}_fn`)
        return [
          `CREATE FUNCTION ${fn}() RETURNS trigger LANGUAGE plpgsql AS ${dollarQuoted(op.body)}`,
          `CREATE TRIGGER ${id(op.name)} ${op.timing} ${op.event} ON ${quoteTable('postgres', ns, op.table)} FOR EACH ROW EXECUTE FUNCTION ${fn}()`,
        ]
      }
      case 'createEvent':
      case 'enableEvent':
      case 'disableEvent':
      case 'dropEvent':
        throw new AdapterError('UNSUPPORTED', 'PostgreSQL has no event scheduler')
      case 'setDatabaseCollation': {
        // A database's collation is fixed when it is created; what can change is each text column's.
        if (!op.applyToTables)
          throw new AdapterError('UNSUPPORTED', 'PostgreSQL cannot change a database collation after creating it')
        return (op.tables ?? []).flatMap((x) => {
          const cols = op.columns?.[x] ?? []
          return cols.length === 0
            ? []
            : pgDdl.build(ns, { op: 'convertCollation', table: x, collation: op.collation, columns: cols })
        })
      }
      case 'dropTables':
        return [`DROP TABLE ${op.tables.map((x) => quoteTable('postgres', ns, x)).join(', ')}`]
      case 'dropObjects':
        return dropOrder(op.objects).map(
          (o) => `DROP ${PG_DROP_KEYWORD[o.kind]} IF EXISTS ${quoteTable('postgres', ns, o.name)} CASCADE`
        )
      case 'truncateTables':
        return [`TRUNCATE TABLE ${op.tables.map((x) => quoteTable('postgres', ns, x)).join(', ')}`]
      case 'maintainTables': {
        const list = op.tables.map((x) => quoteTable('postgres', ns, x)).join(', ')
        switch (op.action) {
          case 'analyze':
            return [`ANALYZE ${list}`]
          case 'vacuum':
            return [`VACUUM (ANALYZE) ${list}`]
          case 'optimize':
            return [`VACUUM (FULL, ANALYZE) ${list}`]
          default:
            throw new AdapterError('UNSUPPORTED', `PostgreSQL has no ${op.action.toUpperCase()} TABLE`)
        }
      }
      case 'renameTables':
        // Renaming keeps each table in its schema; all or none.
        return inTransaction(
          op.renames.map((r) => `ALTER TABLE ${quoteTable('postgres', ns, r.from)} RENAME TO ${id(r.to)}`)
        )
      case 'copyTables':
        return op.tables.flatMap((x) =>
          pgDdl.build(ns, {
            op: 'copyTable',
            table: x,
            newName: x,
            withData: op.withData,
            ...(op.toSchema ? { toSchema: op.toSchema } : {}),
            ...(op.details?.[x] ?? {}),
          })
        )
      default:
        break
    }
    const t = quoteTable('postgres', ns, op.table)
    const schema = id(ns.schema ?? 'public')
    switch (op.op) {
      case 'createTable': {
        const defs = op.columns.map(columnDef)
        if (op.primaryKey.length > 0) defs.push(`PRIMARY KEY (${op.primaryKey.map(id).join(', ')})`)
        if (op.partitionBy?.method === 'key')
          throw new AdapterError('UNSUPPORTED', 'PostgreSQL has no KEY partitioning')
        if (op.engine || op.collation)
          throw new AdapterError('UNSUPPORTED', 'PostgreSQL tables have no engine or collation option')
        const by = op.partitionBy
          ? ` PARTITION BY ${op.partitionBy.method.toUpperCase()} (${op.partitionBy.expression})`
          : ''
        return [
          `CREATE TABLE ${t} (\n  ${defs.join(',\n  ')}\n)${by}`,
          ...(op.comment ? [`COMMENT ON TABLE ${t} IS ${pgLiteral(op.comment)}`] : []),
          ...op.columns.flatMap((c) => commentSql(t, c)),
        ]
      }
      case 'partitionTable':
        throw new AdapterError('UNSUPPORTED', 'PostgreSQL cannot partition an existing table; create it partitioned')
      case 'addPartition':
        // A partition is a table of its own, in the parent's schema.
        if (!op.partition.bound)
          throw new AdapterError('VALIDATION', 'A partition needs its bound (FOR VALUES … or DEFAULT)')
        return [`CREATE TABLE ${quoteTable('postgres', ns, op.partition.name)} PARTITION OF ${t} ${op.partition.bound}`]
      case 'dropPartition':
        return [`DROP TABLE ${quoteTable('postgres', ns, op.name)}`]
      case 'truncatePartition':
        return [`TRUNCATE TABLE ${quoteTable('postgres', ns, op.name)}`]
      case 'detachPartition':
        return [`ALTER TABLE ${t} DETACH PARTITION ${quoteTable('postgres', ns, op.name)}`]
      case 'removePartitioning':
        throw new AdapterError('UNSUPPORTED', 'PostgreSQL cannot turn a partitioned table back into a plain one')
      case 'maintainPartition':
        if (op.action !== 'analyze')
          throw new AdapterError('UNSUPPORTED', `PostgreSQL has no ${op.action} for a partition`)
        return [`ANALYZE ${quoteTable('postgres', ns, op.name)}`]
      case 'addColumn':
        // PostgreSQL cannot position columns; `after` / `first` are ignored.
        return [
          `ALTER TABLE ${t} ADD COLUMN ${columnDef(op.column)}`,
          ...commentSql(t, op.column),
          ...columnKeySql('postgres', ns, op),
        ]
      case 'modifyColumn': {
        const c = op.column
        const prev = op.previous
        if (op.first || op.after) throw new AdapterError('UNSUPPORTED', 'PostgreSQL cannot reorder columns')
        const out: string[] = []
        if (op.name !== c.name) out.push(`ALTER TABLE ${t} RENAME COLUMN ${id(op.name)} TO ${id(c.name)}`)
        const col = id(c.name)
        const generated = generatedChange(t, col, prev === undefined ? undefined : prev.generated, c.generated)
        // With the current definition known, only what changed is emitted: an ALTER TYPE rewrites the table
        // and a DROP DEFAULT the user never asked for is exactly what a reviewing DBA refuses to run.
        if (prev === undefined || prev.dataType !== c.dataType || (prev.collation ?? null) !== c.collation) {
          // A change of type with no implicit conversion (text to integer, say) needs the cast spelled out; when the
          // type is unchanged (only the collation) there is nothing to convert.
          const using = prev !== undefined && prev.dataType !== c.dataType ? ` USING ${col}::${c.dataType}` : ''
          out.push(
            `ALTER TABLE ${t} ALTER COLUMN ${col} TYPE ${c.dataType}${c.collation ? ` COLLATE ${id(c.collation)}` : ''}${using}`
          )
        }
        out.push(...generated)
        if (prev === undefined || prev.nullable !== c.nullable) {
          out.push(`ALTER TABLE ${t} ALTER COLUMN ${col} ${c.nullable ? 'DROP NOT NULL' : 'SET NOT NULL'}`)
        }
        // A serial / identity column keeps its generator: touching DEFAULT would drop nextval() or fail on an
        // identity column. Turning a plain column into an identity one is left to hand-written SQL.
        if (!c.autoIncrement && !c.generated && (prev === undefined || defaultSql(prev) !== defaultSql(c))) {
          const def = defaultSql(c)
          out.push(`ALTER TABLE ${t} ALTER COLUMN ${col} ${def ? `SET DEFAULT ${def}` : 'DROP DEFAULT'}`)
        }
        if (c.comment !== null && (prev === undefined || prev.comment !== c.comment)) {
          out.push(`COMMENT ON COLUMN ${t}.${col} IS ${pgLiteral(c.comment)}`)
        } else if (c.comment === null && prev?.comment != null) {
          out.push(`COMMENT ON COLUMN ${t}.${col} IS NULL`)
        }
        return out
      }
      case 'dropColumn':
        return [`ALTER TABLE ${t} DROP COLUMN ${id(op.name)}`]
      case 'dropColumns':
        return [`ALTER TABLE ${t} ${op.names.map((n) => `DROP COLUMN ${id(n)}`).join(', ')}`]
      case 'modifyColumns':
        // Each change as modifyColumn writes it: only the clauses that differ from the current definition.
        return inTransaction(op.changes.flatMap((c) => pgDdl.build(ns, { op: 'modifyColumn', table: op.table, ...c })))
      case 'reorderColumns':
        throw new AdapterError('UNSUPPORTED', 'PostgreSQL cannot reorder columns')
      case 'setPrimaryKey':
        return [
          `ALTER TABLE ${t} ${op.current ? `DROP CONSTRAINT ${id(op.current)}, ` : ''}ADD PRIMARY KEY (${op.columns.map(id).join(', ')})`,
        ]
      case 'addIndex':
        return [createIndexSql('postgres', ns, op)]
      case 'renameIndex':
        return [`ALTER INDEX ${schema}.${id(op.name)} RENAME TO ${id(op.newName)}`]
      case 'alterIndex':
        return inTransaction([
          `DROP INDEX ${schema}.${id(op.name)}`,
          createIndexSql('postgres', ns, { ...op.index, table: op.table }),
        ])
      case 'dropIndex':
        return [`DROP INDEX ${schema}.${id(op.name)}`]
      case 'addForeignKey':
        return [addForeignKeySql('postgres', ns, op)]
      case 'dropForeignKey':
        return [`ALTER TABLE ${t} DROP CONSTRAINT ${id(op.name)}`]
      case 'dropTable':
        return [
          `DROP ${op.kind === 'materialized_view' ? 'MATERIALIZED VIEW' : op.kind === 'view' ? 'VIEW' : op.kind === 'sequence' ? 'SEQUENCE' : 'TABLE'} ${t}`,
        ]
      case 'truncateTable':
        return [`TRUNCATE TABLE ${t}`]
      case 'renameTable':
        // Renaming keeps the table in its schema; the new name must not be qualified.
        return [`ALTER TABLE ${t} RENAME TO ${id(op.newName)}`]
      case 'setTableOptions':
        if (
          op.engine !== undefined ||
          op.collation !== undefined ||
          op.autoIncrement !== undefined ||
          op.rowFormat !== undefined ||
          op.checksum !== undefined ||
          op.packKeys !== undefined ||
          op.delayKeyWrite !== undefined ||
          op.transactional !== undefined ||
          op.pageChecksum !== undefined ||
          op.statsPersistent !== undefined ||
          op.statsAutoRecalc !== undefined
        ) {
          throw new AdapterError(
            'UNSUPPORTED',
            'PostgreSQL tables have no engine, collation, AUTO_INCREMENT, row format or checksum option'
          )
        }
        if (op.comment === undefined) throw new AdapterError('VALIDATION', 'No table option to change')
        return [`COMMENT ON TABLE ${t} IS ${op.comment === null ? 'NULL' : pgLiteral(op.comment)}`]
      case 'maintainTable':
        switch (op.action) {
          case 'analyze':
            return [`ANALYZE ${t}`]
          case 'vacuum':
            return [`VACUUM (ANALYZE) ${t}`]
          case 'optimize':
            return [`VACUUM (FULL, ANALYZE) ${t}`]
          case 'check':
            throw new AdapterError('UNSUPPORTED', 'PostgreSQL has no CHECK TABLE')
          case 'repair':
            throw new AdapterError('UNSUPPORTED', 'PostgreSQL has no REPAIR TABLE')
          case 'checksum':
          case 'flush':
            throw new AdapterError('UNSUPPORTED', `PostgreSQL has no ${op.action.toUpperCase()} TABLE`)
        }
        break
      case 'convertCollation': {
        // Each text column keeps its type and takes the collation, all in one ALTER.
        const cols = op.columns ?? []
        if (cols.length === 0) throw new AdapterError('VALIDATION', 'No text column to change')
        const collation = id(op.collation)
        return [
          `ALTER TABLE ${t} ${cols.map((c) => `ALTER COLUMN ${id(c.name)} TYPE ${c.dataType} COLLATE ${collation}`).join(', ')}`,
        ]
      }
      case 'orderTable':
        if (!op.index) throw new AdapterError('VALIDATION', 'PostgreSQL orders a table along an index (CLUSTER)')
        return [`CLUSTER ${t} USING ${id(op.index)}`]
      case 'copyTable': {
        const into: Namespace = {
          database: ns.database,
          ...((op.toSchema ?? ns.schema) ? { schema: op.toSchema ?? ns.schema } : {}),
        }
        const target = quoteTable('postgres', into, op.newName)
        // Rows only go into a table that is there: dropping it first would leave nothing to insert into.
        if (op.dropExisting && op.structure === false)
          throw new AdapterError('VALIDATION', 'A data-only copy cannot drop the table it copies into')
        const out = op.dropExisting ? [`DROP TABLE IF EXISTS ${target}`] : []
        // INCLUDING ALL keeps defaults, constraints (incl. PK), indexes and comments; foreign keys are added after.
        if (op.structure !== false) out.push(`CREATE TABLE ${target} (LIKE ${t} INCLUDING ALL)`)
        if (op.withData) {
          // OVERRIDING SYSTEM VALUE keeps GENERATED ALWAYS AS IDENTITY values; generated columns are left out by the caller.
          const cols = op.columns?.map(id).join(', ')
          out.push(
            cols
              ? `INSERT INTO ${target} (${cols}) OVERRIDING SYSTEM VALUE SELECT ${cols} FROM ${t}`
              : `INSERT INTO ${target} OVERRIDING SYSTEM VALUE SELECT * FROM ${t}`
          )
        }
        // LIKE copies a serial column's DEFAULT nextval('<source>_seq'): the copy would draw ids from the
        // source's sequence and pin it (DROP TABLE source then fails). Give the copy its own sequence, as
        // MySQL's CREATE TABLE ... LIKE gives it its own AUTO_INCREMENT.
        for (const c of op.structure === false ? [] : (op.serialColumns ?? [])) {
          const seq = quoteTable('postgres', into, `${op.newName}_${c}_seq`)
          out.push(
            `CREATE SEQUENCE ${seq} OWNED BY ${target}.${id(c)}`,
            `ALTER TABLE ${target} ALTER COLUMN ${id(c)} SET DEFAULT nextval(${pgLiteral(seq)}::regclass)`
          )
        }
        if (op.withData) {
          // INCLUDING IDENTITY gives the copy fresh sequences starting at their minimum: advance them past the
          // copied ids, exactly as the SQL dump does, or the first insert into the copy collides.
          for (const c of [...(op.identityColumns ?? []), ...(op.serialColumns ?? [])]) {
            out.push(pgAdvanceSequence(target, c))
          }
        }
        for (const fk of op.foreignKeys ?? [])
          out.push(
            addForeignKeySql('postgres', into, {
              op: 'addForeignKey',
              table: op.newName,
              ...fk,
              ...((fk.refSchema ?? ns.schema) ? { refSchema: fk.refSchema ?? ns.schema } : {}),
            })
          )
        return out
      }
    }
  },
}
