import type { ColumnSpec, DdlOp, Namespace, TableSchema } from '@tsmyadmin/shared'
import { pgLiteral } from '../sql/literal.ts'
import { quoteIdent, quoteTable } from '../sql/quote.ts'
import { AdapterError, type DdlBuilder } from '../types.ts'

const id = (s: string) => quoteIdent('postgres', s)

function defaultSql(c: ColumnSpec): string | null {
  if (!c.default) return null
  return c.default.kind === 'literal' ? pgLiteral(c.default.value) : c.default.sql
}

function columnDef(c: ColumnSpec): string {
  const parts = [id(c.name), c.dataType]
  if (c.autoIncrement) parts.push('GENERATED BY DEFAULT AS IDENTITY')
  if (!c.nullable) parts.push('NOT NULL')
  const def = defaultSql(c)
  if (def) parts.push(`DEFAULT ${def}`)
  return parts.join(' ')
}

function commentSql(t: string, c: ColumnSpec): string[] {
  return c.comment === null ? [] : [`COMMENT ON COLUMN ${t}.${id(c.name)} IS ${pgLiteral(c.comment)}`]
}

export const pgDdl: DdlBuilder = {
  build(ns: Namespace, op: DdlOp): string[] {
    // Database-level ops have no table; handle them before touching op.table.
    switch (op.op) {
      case 'createDatabase':
        return [`CREATE DATABASE ${id(op.name)}`]
      case 'createSchema':
        return [`CREATE SCHEMA ${id(op.name)}`]
      case 'dropDatabase':
        return [`DROP DATABASE ${id(op.name)}`]
      case 'enableEvent':
      case 'disableEvent':
      case 'dropEvent':
        throw new AdapterError('UNSUPPORTED', 'PostgreSQL has no event scheduler')
      default:
        break
    }
    const t = quoteTable('postgres', ns, op.table)
    const schema = id(ns.schema ?? 'public')
    switch (op.op) {
      case 'createTable': {
        const defs = op.columns.map(columnDef)
        if (op.primaryKey.length > 0) defs.push(`PRIMARY KEY (${op.primaryKey.map(id).join(', ')})`)
        return [`CREATE TABLE ${t} (\n  ${defs.join(',\n  ')}\n)`, ...op.columns.flatMap((c) => commentSql(t, c))]
      }
      case 'addColumn':
        // PostgreSQL cannot position columns; `after` is ignored.
        return [`ALTER TABLE ${t} ADD COLUMN ${columnDef(op.column)}`, ...commentSql(t, op.column)]
      case 'modifyColumn': {
        const c = op.column
        const out: string[] = []
        if (op.name !== c.name) out.push(`ALTER TABLE ${t} RENAME COLUMN ${id(op.name)} TO ${id(c.name)}`)
        const col = id(c.name)
        out.push(`ALTER TABLE ${t} ALTER COLUMN ${col} TYPE ${c.dataType}`)
        out.push(`ALTER TABLE ${t} ALTER COLUMN ${col} ${c.nullable ? 'DROP NOT NULL' : 'SET NOT NULL'}`)
        const def = defaultSql(c)
        out.push(`ALTER TABLE ${t} ALTER COLUMN ${col} ${def ? `SET DEFAULT ${def}` : 'DROP DEFAULT'}`)
        if (c.comment !== null) out.push(`COMMENT ON COLUMN ${t}.${col} IS ${pgLiteral(c.comment)}`)
        return out
      }
      case 'dropColumn':
        return [`ALTER TABLE ${t} DROP COLUMN ${id(op.name)}`]
      case 'addIndex':
        return [`CREATE ${op.unique ? 'UNIQUE ' : ''}INDEX ${id(op.name)} ON ${t} (${op.columns.map(id).join(', ')})`]
      case 'dropIndex':
        return [`DROP INDEX ${schema}.${id(op.name)}`]
      case 'dropTable':
        return [`DROP TABLE ${t}`]
      case 'truncateTable':
        return [`TRUNCATE TABLE ${t}`]
      case 'renameTable':
        // Renaming keeps the table in its schema; the new name must not be qualified.
        return [`ALTER TABLE ${t} RENAME TO ${id(op.newName)}`]
      case 'copyTable': {
        const target = quoteTable('postgres', ns, op.newName)
        // INCLUDING ALL keeps defaults, constraints (incl. PK), indexes and comments; foreign keys are not copied.
        const out = [`CREATE TABLE ${target} (LIKE ${t} INCLUDING ALL)`]
        if (op.withData) out.push(`INSERT INTO ${target} SELECT * FROM ${t}`)
        return out
      }
    }
  },
}

const PLAIN_IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/
/** Index/constraint column entries may be expressions (from pg_get_indexdef); quote only plain names. */
const indexCol = (c: string) => (PLAIN_IDENT.test(c) ? id(c) : c)

/** Reconstructs CREATE TABLE + indexes + foreign keys + comments from catalog metadata (see PostgresAdapter.showCreateTable). */
export function pgCreateStatements(ns: Namespace, schema: TableSchema): string[] {
  const t = quoteTable('postgres', ns, schema.name)
  const defs = schema.columns.map((c) => {
    const identity = c.extra.startsWith('identity') || c.extra === 'serial'
    const parts = [id(c.name), c.dataType]
    if (identity)
      parts.push(c.extra === 'identity always' ? 'GENERATED ALWAYS AS IDENTITY' : 'GENERATED BY DEFAULT AS IDENTITY')
    if (!c.nullable) parts.push('NOT NULL')
    if (c.default !== null && !identity) parts.push(`DEFAULT ${c.default}`)
    return parts.join(' ')
  })
  if (schema.primaryKey.length > 0) defs.push(`PRIMARY KEY (${schema.primaryKey.map(id).join(', ')})`)
  const out = [`CREATE TABLE ${t} (\n  ${defs.join(',\n  ')}\n)`]
  for (const i of schema.indexes) {
    if (i.primary) continue
    out.push(`CREATE ${i.unique ? 'UNIQUE ' : ''}INDEX ${id(i.name)} ON ${t} (${i.columns.map(indexCol).join(', ')})`)
  }
  for (const fk of schema.foreignKeys) {
    const ref = quoteTable('postgres', fk.refNamespace, fk.refTable)
    const actions = [
      fk.onUpdate ? ` ON UPDATE ${fk.onUpdate}` : '',
      fk.onDelete ? ` ON DELETE ${fk.onDelete}` : '',
    ].join('')
    out.push(
      `ALTER TABLE ${t} ADD CONSTRAINT ${id(fk.name)} FOREIGN KEY (${fk.columns.map(id).join(', ')}) REFERENCES ${ref} (${fk.refColumns.map(id).join(', ')})${actions}`
    )
  }
  if (schema.comment !== null) out.push(`COMMENT ON TABLE ${t} IS ${pgLiteral(schema.comment)}`)
  for (const c of schema.columns)
    if (c.comment !== null) out.push(`COMMENT ON COLUMN ${t}.${id(c.name)} IS ${pgLiteral(c.comment)}`)
  return out
}
