import type { DdlOp, Namespace } from '@tsmyadmin/shared'
import { describe, expect, it } from 'vitest'
import { pgDdl } from '../postgres/ddl.ts'
import { pgAdvanceSequence } from '../postgres/export.ts'
import { col, refuses } from './ddl-helpers.ts'

/** The options, refusals and edges of the PostgreSQL DDL builder (the counterpart of the MySQL details). */

const ns: Namespace = { database: 'd', schema: 's' }
const pg = (op: DdlOp, space: Namespace = ns) => pgDdl.build(space, op)
/** The statements of an addColumn, where the column's definition is the first. */
const columnSql = (c: ReturnType<typeof col>) =>
  (pg({ op: 'addColumn', table: 't', column: c })[0] ?? '').replace('ALTER TABLE "s"."t" ADD COLUMN ', '')

describe('PostgreSQL: databases and schemas', () => {
  it('creates a database, from template0 with the collation when one is given', () => {
    expect(pg({ op: 'createDatabase', name: 'x' })).toEqual(['CREATE DATABASE "x"'])
    expect(pg({ op: 'createDatabase', name: 'x', collation: 'C' })).toEqual([
      `CREATE DATABASE "x" TEMPLATE template0 LC_COLLATE 'C' LC_CTYPE 'C'`,
    ])
    expect(pg({ op: 'createSchema', name: 'x' })).toEqual(['CREATE SCHEMA "x"'])
  })

  it('drops databases with FORCE, and sets a server variable through ALTER SYSTEM and a reload', () => {
    expect(pg({ op: 'dropDatabase', name: 'x' })).toEqual(['DROP DATABASE "x" WITH (FORCE)'])
    expect(pg({ op: 'dropDatabases', names: ['b', 'a'] })).toEqual([
      'DROP DATABASE "b" WITH (FORCE)',
      'DROP DATABASE "a" WITH (FORCE)',
    ])
    expect(pg({ op: 'setServerVariable', name: 'work_mem', value: '8MB' })).toEqual([
      `ALTER SYSTEM SET work_mem = '8MB'`,
      'SELECT pg_reload_conf()',
    ])
    expect(pg({ op: 'setServerVariable', name: 'work_mem' })).toEqual([
      'ALTER SYSTEM RESET work_mem',
      'SELECT pg_reload_conf()',
    ])
  })

  it("renames or copies a database after ending only this tool's own idle connections to it", () => {
    const release = (db: string) =>
      `SELECT pg_terminate_backend(pid, 5000) FROM pg_stat_activity WHERE datname = '${db}' AND application_name = 'tsmyadmin' AND usename = session_user AND state = 'idle' AND pid <> pg_backend_pid()`
    expect(pg({ op: 'renameDatabase', name: 'a', newName: 'b' })).toEqual([
      release('a'),
      'ALTER DATABASE "a" RENAME TO "b"',
    ])
    expect(pg({ op: 'copyDatabase', name: 'a', newName: 'b', withData: true })).toEqual([
      release('a'),
      'CREATE DATABASE "b" TEMPLATE "a"',
    ])
    expect(pg({ op: 'copyDatabase', name: 'a', newName: 'b', withData: true, structure: true })).toHaveLength(2)
    refuses(
      () => pg({ op: 'copyDatabase', name: 'a', newName: 'b', withData: false }),
      'UNSUPPORTED',
      /structure and its data/
    )
    refuses(
      () => pg({ op: 'copyDatabase', name: 'a', newName: 'b', withData: true, structure: false }),
      'UNSUPPORTED',
      /structure and its data/
    )
  })

  it('moves a table to another schema, and changes text column collations only, since the database one is fixed', () => {
    expect(pg({ op: 'moveTable', table: 't', to: 'z' })).toEqual(['ALTER TABLE "s"."t" SET SCHEMA "z"'])
    refuses(
      () => pg({ op: 'setDatabaseCollation', name: 'd', collation: 'C', applyToTables: false }),
      'UNSUPPORTED',
      /cannot change a database collation/
    )
    expect(
      pg({
        op: 'setDatabaseCollation',
        name: 'd',
        collation: 'C',
        applyToTables: true,
        tables: ['a', 'b', 'c'],
        columns: { a: [{ name: 'x', dataType: 'text' }], b: [] },
      })
    ).toEqual(['ALTER TABLE "s"."a" ALTER COLUMN "x" TYPE text COLLATE "C"'])
    expect(pg({ op: 'setDatabaseCollation', name: 'd', collation: 'C', applyToTables: true })).toEqual([])
    // Tables named but no column list for them: nothing to convert, and no failure.
    expect(pg({ op: 'setDatabaseCollation', name: 'd', collation: 'C', applyToTables: true, tables: ['a'] })).toEqual(
      []
    )
  })
})

describe('PostgreSQL: a column definition', () => {
  it('writes collation, identity, NOT NULL and default in order', () => {
    expect(
      columnSql(
        col('c', 'text', {
          collation: 'C',
          autoIncrement: true,
          nullable: false,
          default: { kind: 'literal', value: "it's" },
        })
      )
    ).toBe(`"c" text COLLATE "C" GENERATED BY DEFAULT AS IDENTITY NOT NULL DEFAULT 'it''s'`)
    expect(columnSql(col('c', 'int'))).toBe('"c" int')
    expect(columnSql(col('c', 'int', { default: { kind: 'expression', sql: 'now()' } }))).toBe('"c" int DEFAULT now()')
    expect(columnSql(col('c', 'text', { default: { kind: 'literal', value: '' } }))).toBe(`"c" text DEFAULT ''`)
  })

  it('writes a generated column without identity or default, and says NOT NULL only when it is', () => {
    expect(
      columnSql(
        col('g', 'int', {
          generated: { expression: 'a + 1', stored: true },
          autoIncrement: true,
          default: { kind: 'literal', value: '1' },
        })
      )
    ).toBe('"g" int GENERATED ALWAYS AS (a + 1) STORED')
    expect(
      columnSql(col('g', 'int', { generated: { expression: 'a', stored: false }, nullable: false, collation: 'C' }))
    ).toBe('"g" int COLLATE "C" GENERATED ALWAYS AS (a) VIRTUAL NOT NULL')
  })

  it('adds the column comment after the column, and none when it has none', () => {
    expect(pg({ op: 'addColumn', table: 't', column: col('c', 'int', { comment: "it's" }) })).toEqual([
      'ALTER TABLE "s"."t" ADD COLUMN "c" int',
      `COMMENT ON COLUMN "s"."t"."c" IS 'it''s'`,
    ])
    expect(pg({ op: 'addColumn', table: 't', column: col('c', 'int', { comment: '' }) })[1]).toBe(
      `COMMENT ON COLUMN "s"."t"."c" IS ''`
    )
    expect(pg({ op: 'addColumn', table: 't', column: col('c', 'int'), after: 'x', first: true })).toEqual([
      'ALTER TABLE "s"."t" ADD COLUMN "c" int',
    ])
  })
})

describe('PostgreSQL: modifying a column', () => {
  const modify = (
    column: ReturnType<typeof col>,
    previous?: ReturnType<typeof col>,
    extra: Record<string, unknown> = {}
  ) =>
    pg({
      op: 'modifyColumn',
      table: 't',
      name: column.name,
      column,
      ...(previous ? { previous } : {}),
      ...extra,
    } as DdlOp)

  it('writes every clause when the current definition is not known', () => {
    expect(
      modify(col('c', 'bigint', { nullable: false, default: { kind: 'literal', value: '1' }, comment: 'k' }))
    ).toEqual([
      'ALTER TABLE "s"."t" ALTER COLUMN "c" TYPE bigint',
      'ALTER TABLE "s"."t" ALTER COLUMN "c" SET NOT NULL',
      `ALTER TABLE "s"."t" ALTER COLUMN "c" SET DEFAULT '1'`,
      `COMMENT ON COLUMN "s"."t"."c" IS 'k'`,
    ])
    expect(modify(col('c', 'int'))).toEqual([
      'ALTER TABLE "s"."t" ALTER COLUMN "c" TYPE int',
      'ALTER TABLE "s"."t" ALTER COLUMN "c" DROP NOT NULL',
      'ALTER TABLE "s"."t" ALTER COLUMN "c" DROP DEFAULT',
    ])
  })

  it('writes only what changed when the current definition is known', () => {
    const before = col('c', 'int', { default: { kind: 'literal', value: '1' }, comment: 'old' })
    expect(modify(before, before)).toEqual([])
    expect(modify({ ...before, dataType: 'text' }, before)).toEqual([
      'ALTER TABLE "s"."t" ALTER COLUMN "c" TYPE text USING "c"::text',
    ])
    expect(modify({ ...before, collation: 'C' }, before)).toEqual([
      'ALTER TABLE "s"."t" ALTER COLUMN "c" TYPE int COLLATE "C"',
    ])
    expect(modify({ ...before, nullable: false }, before)).toEqual([
      'ALTER TABLE "s"."t" ALTER COLUMN "c" SET NOT NULL',
    ])
    expect(modify({ ...before, default: null }, before)).toEqual(['ALTER TABLE "s"."t" ALTER COLUMN "c" DROP DEFAULT'])
    expect(modify(col('c', 'int', { ...before, default: { kind: 'expression', sql: '2' } }), before)).toEqual([
      'ALTER TABLE "s"."t" ALTER COLUMN "c" SET DEFAULT 2',
    ])
    expect(modify({ ...before, comment: 'new' }, before)).toEqual([`COMMENT ON COLUMN "s"."t"."c" IS 'new'`])
    expect(modify({ ...before, comment: null }, before)).toEqual(['COMMENT ON COLUMN "s"."t"."c" IS NULL'])
    expect(
      modify(col('c', 'int', { ...before, comment: null }), col('c', 'int', { ...before, comment: null }))
    ).toEqual([])
  })

  it('renames first, and leaves the default of an identity or generated column alone', () => {
    const before = col('a', 'int', { autoIncrement: true })
    expect(modify(col('b', 'int', { autoIncrement: true }), before, { name: 'a' })).toEqual([
      'ALTER TABLE "s"."t" RENAME COLUMN "a" TO "b"',
    ])
    expect(
      modify(
        col('c', 'int', { autoIncrement: true, default: { kind: 'literal', value: '1' } }),
        col('c', 'int', { autoIncrement: true })
      )
    ).toEqual([])
  })

  it('changes a generation expression, drops it, and refuses what PostgreSQL cannot do in place', () => {
    const gen = (expression: string, stored = true) => col('c', 'int', { generated: { expression, stored } })
    expect(modify(gen('a'), undefined).some((s) => s.includes('SET EXPRESSION AS (a)'))).toBe(true)
    expect(modify(gen('b'), gen('a'))).toEqual(['ALTER TABLE "s"."t" ALTER COLUMN "c" SET EXPRESSION AS (b)'])
    expect(modify(gen('a'), gen('a'))).toEqual([])
    expect(modify(col('c', 'int'), gen('a'))).toEqual(['ALTER TABLE "s"."t" ALTER COLUMN "c" DROP EXPRESSION'])
    expect(modify(col('c', 'int'), col('c', 'int'))).toEqual([])
    refuses(() => modify(gen('a'), col('c', 'int')), 'UNSUPPORTED', /cannot make an existing column generated/)
    refuses(() => modify(gen('a', false), gen('a', true)), 'UNSUPPORTED', /how it is kept/)
  })

  it('refuses to reorder, and changes several columns together in one transaction', () => {
    refuses(() => modify(col('c', 'int'), undefined, { first: true }), 'UNSUPPORTED', /cannot reorder columns/)
    refuses(() => modify(col('c', 'int'), undefined, { after: 'x' }), 'UNSUPPORTED', /cannot reorder columns/)
    refuses(
      () => pg({ op: 'reorderColumns', table: 't', columns: [col('a', 'int'), col('b', 'int')] }),
      'UNSUPPORTED',
      /cannot reorder columns/
    )
    const before = col('a', 'int')
    const out = pg({
      op: 'modifyColumns',
      table: 't',
      changes: [
        { name: 'a', column: col('a', 'text'), previous: before },
        { name: 'b', column: col('b', 'int', { nullable: false }), previous: col('b', 'int') },
      ],
    })
    expect(out[0]).toBe('BEGIN')
    expect(out.at(-1)).toBe('COMMIT')
    expect(out).toContain('ALTER TABLE "s"."t" ALTER COLUMN "b" SET NOT NULL')
    expect(
      pg({ op: 'modifyColumns', table: 't', changes: [{ name: 'a', column: col('a', 'text'), previous: before }] })
    ).toEqual(['ALTER TABLE "s"."t" ALTER COLUMN "a" TYPE text USING "a"::text'])
  })
})

describe('PostgreSQL: tables, keys and indexes', () => {
  const create = (extra: Record<string, unknown> = {}) =>
    pg({
      op: 'createTable',
      table: 't',
      columns: [col('id', 'int', { comment: 'k' })],
      primaryKey: [],
      ...extra,
    } as DdlOp)

  it('creates a table with its primary key, partitioning and comments', () => {
    expect(create()).toEqual(['CREATE TABLE "s"."t" (\n  "id" int\n)', `COMMENT ON COLUMN "s"."t"."id" IS 'k'`])
    expect(create({ primaryKey: ['id'], comment: "it's", partitionBy: { method: 'range', expression: 'id' } })).toEqual(
      [
        'CREATE TABLE "s"."t" (\n  "id" int,\n  PRIMARY KEY ("id")\n) PARTITION BY RANGE (id)',
        `COMMENT ON TABLE "s"."t" IS 'it''s'`,
        `COMMENT ON COLUMN "s"."t"."id" IS 'k'`,
      ]
    )
    expect(create({ columns: [col('id', 'int'), col('x', 'int')], primaryKey: ['id', 'x'] })[0]).toContain(
      'PRIMARY KEY ("id", "x")'
    )
    refuses(() => create({ partitionBy: { method: 'key', expression: 'id' } }), 'UNSUPPORTED', /no KEY partitioning/)
    refuses(() => create({ engine: 'InnoDB' }), 'UNSUPPORTED', /no engine or collation/)
    refuses(() => create({ collation: 'C' }), 'UNSUPPORTED', /no engine or collation/)
  })

  it('works on partitions as tables of their own', () => {
    expect(
      pg({ op: 'addPartition', table: 't', partition: { name: 'p', bound: 'FOR VALUES FROM (1) TO (2)' } })
    ).toEqual(['CREATE TABLE "s"."p" PARTITION OF "s"."t" FOR VALUES FROM (1) TO (2)'])
    refuses(
      () => pg({ op: 'addPartition', table: 't', partition: { name: 'p', bound: '' } }),
      'VALIDATION',
      /needs its bound/
    )
    expect(pg({ op: 'dropPartition', table: 't', name: 'p' })).toEqual(['DROP TABLE "s"."p"'])
    expect(pg({ op: 'truncatePartition', table: 't', name: 'p' })).toEqual(['TRUNCATE TABLE "s"."p"'])
    expect(pg({ op: 'detachPartition', table: 't', name: 'p' })).toEqual([
      'ALTER TABLE "s"."t" DETACH PARTITION "s"."p"',
    ])
    expect(pg({ op: 'maintainPartition', table: 't', name: 'p', action: 'analyze' })).toEqual(['ANALYZE "s"."p"'])
    refuses(
      () => pg({ op: 'maintainPartition', table: 't', name: 'p', action: 'rebuild' }),
      'UNSUPPORTED',
      /no rebuild for a partition/
    )
    refuses(() => pg({ op: 'removePartitioning', table: 't' }), 'UNSUPPORTED', /back into a plain one/)
    refuses(
      () => pg({ op: 'partitionTable', table: 't', method: 'hash', expression: 'id', partitions: [] }),
      'UNSUPPORTED',
      /cannot partition an existing table/
    )
  })

  it('replaces the primary key, renames and replaces indexes, and drops constraints', () => {
    expect(pg({ op: 'setPrimaryKey', table: 't', columns: ['a', 'b'] })).toEqual([
      'ALTER TABLE "s"."t" ADD PRIMARY KEY ("a", "b")',
    ])
    expect(pg({ op: 'setPrimaryKey', table: 't', columns: ['a'], current: 't_pkey' })).toEqual([
      'ALTER TABLE "s"."t" DROP CONSTRAINT "t_pkey", ADD PRIMARY KEY ("a")',
    ])
    expect(pg({ op: 'renameIndex', table: 't', name: 'i', newName: 'j' })).toEqual([
      'ALTER INDEX "s"."i" RENAME TO "j"',
    ])
    expect(pg({ op: 'dropIndex', table: 't', name: 'i' })).toEqual(['DROP INDEX "s"."i"'])
    expect(pg({ op: 'dropForeignKey', table: 't', name: 'k' })).toEqual(['ALTER TABLE "s"."t" DROP CONSTRAINT "k"'])
    const out = pg({ op: 'alterIndex', table: 't', name: 'i', index: { name: 'j', columns: ['a'], unique: false } })
    expect(out[0]).toBe('BEGIN')
    expect(out[1]).toBe('DROP INDEX "s"."i"')
    expect(out[2]).toMatch(/^CREATE INDEX "j" ON "s"\."t"/)
    expect(out[3]).toBe('COMMIT')
  })

  it('uses the public schema for an index when no schema is given', () => {
    expect(pg({ op: 'dropIndex', table: 't', name: 'i' }, { database: 'd' })).toEqual(['DROP INDEX "public"."i"'])
  })

  it('drops, renames and empties tables, views and sequences', () => {
    const drop = (kind: string) => pg({ op: 'dropTable', table: 't', kind } as DdlOp)
    expect(drop('table')).toEqual(['DROP TABLE "s"."t"'])
    expect(drop('view')).toEqual(['DROP VIEW "s"."t"'])
    expect(drop('materialized_view')).toEqual(['DROP MATERIALIZED VIEW "s"."t"'])
    expect(drop('sequence')).toEqual(['DROP SEQUENCE "s"."t"'])
    expect(pg({ op: 'truncateTable', table: 't' })).toEqual(['TRUNCATE TABLE "s"."t"'])
    expect(pg({ op: 'truncateTables', tables: ['a', 'b'] })).toEqual(['TRUNCATE TABLE "s"."a", "s"."b"'])
    expect(pg({ op: 'dropTables', tables: ['a', 'b'] })).toEqual(['DROP TABLE "s"."a", "s"."b"'])
    expect(pg({ op: 'renameTable', table: 't', newName: 'u' })).toEqual(['ALTER TABLE "s"."t" RENAME TO "u"'])
    expect(pg({ op: 'renameTables', renames: [{ from: 'a', to: 'b' }] })).toEqual(['ALTER TABLE "s"."a" RENAME TO "b"'])
    expect(
      pg({
        op: 'renameTables',
        renames: [
          { from: 'a', to: 'b' },
          { from: 'c', to: 'd' },
        ],
      })
    ).toEqual(['BEGIN', 'ALTER TABLE "s"."a" RENAME TO "b"', 'ALTER TABLE "s"."c" RENAME TO "d"', 'COMMIT'])
    const objects = pg({
      op: 'dropObjects',
      objects: [
        { kind: 'table', name: 't' },
        { kind: 'materialized_view', name: 'm' },
        { kind: 'sequence', name: 's' },
        { kind: 'view', name: 'v' },
      ],
    })
    expect(objects).toContain('DROP TABLE IF EXISTS "s"."t" CASCADE')
    expect(objects).toContain('DROP MATERIALIZED VIEW IF EXISTS "s"."m" CASCADE')
    expect(objects).toContain('DROP SEQUENCE IF EXISTS "s"."s" CASCADE')
    expect(objects).toContain('DROP VIEW IF EXISTS "s"."v" CASCADE')
  })
})

describe('PostgreSQL: table options, maintenance and ordering', () => {
  it('sets only the table comment, clears it with NULL, and refuses MySQL options or no option', () => {
    expect(pg({ op: 'setTableOptions', table: 't', comment: "it's" })).toEqual([`COMMENT ON TABLE "s"."t" IS 'it''s'`])
    expect(pg({ op: 'setTableOptions', table: 't', comment: null })).toEqual(['COMMENT ON TABLE "s"."t" IS NULL'])
    expect(pg({ op: 'setTableOptions', table: 't', comment: '' })).toEqual([`COMMENT ON TABLE "s"."t" IS ''`])
    refuses(() => pg({ op: 'setTableOptions', table: 't' }), 'VALIDATION', /No table option to change/)
    for (const opt of [
      { engine: 'InnoDB' },
      { collation: 'C' },
      { autoIncrement: '1' },
      { rowFormat: 'DYNAMIC' },
      { checksum: true },
      { packKeys: '1' },
      { delayKeyWrite: true },
      { transactional: true },
      { pageChecksum: true },
      { statsPersistent: '1' },
      { statsAutoRecalc: '1' },
    ]) {
      refuses(
        () => pg({ op: 'setTableOptions', table: 't', comment: 'c', ...opt } as DdlOp),
        'UNSUPPORTED',
        /no engine, collation/
      )
    }
  })

  it('maintains a table with ANALYZE or VACUUM, and refuses the actions MySQL has', () => {
    const one = (action: string) => pg({ op: 'maintainTable', table: 't', action } as DdlOp)
    expect(one('analyze')).toEqual(['ANALYZE "s"."t"'])
    expect(one('vacuum')).toEqual(['VACUUM (ANALYZE) "s"."t"'])
    expect(one('optimize')).toEqual(['VACUUM (FULL, ANALYZE) "s"."t"'])
    refuses(() => one('check'), 'UNSUPPORTED', /no CHECK TABLE/)
    refuses(() => one('repair'), 'UNSUPPORTED', /no REPAIR TABLE/)
    refuses(() => one('checksum'), 'UNSUPPORTED', /no CHECKSUM TABLE/)
    refuses(() => one('flush'), 'UNSUPPORTED', /no FLUSH TABLE/)
    const many = (action: string) => pg({ op: 'maintainTables', tables: ['a', 'b'], action } as DdlOp)
    expect(many('analyze')).toEqual(['ANALYZE "s"."a", "s"."b"'])
    expect(many('vacuum')).toEqual(['VACUUM (ANALYZE) "s"."a", "s"."b"'])
    expect(many('optimize')).toEqual(['VACUUM (FULL, ANALYZE) "s"."a", "s"."b"'])
    refuses(() => many('check'), 'UNSUPPORTED', /no CHECK TABLE/)
  })

  it('converts text columns to a collation in one ALTER, and orders a table along an index', () => {
    expect(
      pg({
        op: 'convertCollation',
        table: 't',
        collation: 'C',
        columns: [
          { name: 'a', dataType: 'text' },
          { name: 'b', dataType: 'varchar(9)' },
        ],
      })
    ).toEqual([
      'ALTER TABLE "s"."t" ALTER COLUMN "a" TYPE text COLLATE "C", ALTER COLUMN "b" TYPE varchar(9) COLLATE "C"',
    ])
    refuses(
      () => pg({ op: 'convertCollation', table: 't', collation: 'C', columns: [] }),
      'VALIDATION',
      /No text column/
    )
    refuses(() => pg({ op: 'convertCollation', table: 't', collation: 'C' }), 'VALIDATION', /No text column/)
    expect(pg({ op: 'orderTable', table: 't', index: 'i' })).toEqual(['CLUSTER "s"."t" USING "i"'])
    refuses(() => pg({ op: 'orderTable', table: 't', column: 'a' }), 'VALIDATION', /along an index/)
  })
})

describe('PostgreSQL: copying a table', () => {
  const copy = (extra: Record<string, unknown> = {}) =>
    pg({ op: 'copyTable', table: 't', newName: 'u', withData: true, ...extra } as DdlOp)

  it('creates the copy like the source with everything, and fills it keeping identity values', () => {
    expect(copy()).toEqual([
      'CREATE TABLE "s"."u" (LIKE "s"."t" INCLUDING ALL)',
      'INSERT INTO "s"."u" OVERRIDING SYSTEM VALUE SELECT * FROM "s"."t"',
    ])
    expect(copy({ columns: ['a', 'b'] })[1]).toBe(
      'INSERT INTO "s"."u" ("a", "b") OVERRIDING SYSTEM VALUE SELECT "a", "b" FROM "s"."t"'
    )
    expect(copy({ columns: [] })[1]).toBe('INSERT INTO "s"."u" OVERRIDING SYSTEM VALUE SELECT * FROM "s"."t"')
    expect(copy({ withData: false })).toEqual(['CREATE TABLE "s"."u" (LIKE "s"."t" INCLUDING ALL)'])
  })

  it('copies into another schema, drops a table of that name first, and can copy rows only', () => {
    expect(copy({ toSchema: 'z', withData: false, dropExisting: true })).toEqual([
      'DROP TABLE IF EXISTS "z"."u"',
      'CREATE TABLE "z"."u" (LIKE "s"."t" INCLUDING ALL)',
    ])
    expect(copy({ structure: false })).toEqual(['INSERT INTO "s"."u" OVERRIDING SYSTEM VALUE SELECT * FROM "s"."t"'])
    expect(copy({ structure: true, withData: false })).toHaveLength(1)
    refuses(() => copy({ structure: false, dropExisting: true }), 'VALIDATION', /cannot drop the table it copies into/)
    expect(copy({ withData: false })).toHaveLength(1)
    expect(pg({ op: 'copyTable', table: 't', newName: 'u', withData: false }, { database: 'd' })).toEqual([
      'CREATE TABLE "public"."u" (LIKE "public"."t" INCLUDING ALL)',
    ])
  })

  it('gives a serial column of the copy its own sequence, and advances the sequences past the copied ids', () => {
    const out = copy({ serialColumns: ['n'], identityColumns: ['i'] })
    expect(out).toContain('CREATE SEQUENCE "s"."u_n_seq" OWNED BY "s"."u"."n"')
    expect(out).toContain(`ALTER TABLE "s"."u" ALTER COLUMN "n" SET DEFAULT nextval('"s"."u_n_seq"'::regclass)`)
    expect(out).toContain(pgAdvanceSequence('"s"."u"', 'i'))
    expect(out).toContain(pgAdvanceSequence('"s"."u"', 'n'))
    // Rows only: the table already has its own sequences, and without rows nothing needs advancing.
    const rowsOnly = copy({ structure: false, serialColumns: ['n'], identityColumns: ['i'] })
    expect(rowsOnly.some((s) => s.startsWith('CREATE SEQUENCE'))).toBe(false)
    expect(rowsOnly).toContain(pgAdvanceSequence('"s"."u"', 'i'))
    const noRows = copy({ withData: false, serialColumns: ['n'], identityColumns: ['i'] })
    expect(noRows).toContain('CREATE SEQUENCE "s"."u_n_seq" OWNED BY "s"."u"."n"')
    expect(noRows).not.toContain(pgAdvanceSequence('"s"."u"', 'i'))
    expect(noRows).not.toContain(pgAdvanceSequence('"s"."u"', 'n'))
  })

  it('adds foreign keys to the copy, in the schema they point at', () => {
    const fk = { name: 'k', columns: ['x'], refTable: 'p', refColumns: ['id'] }
    expect(copy({ withData: false, toSchema: 'z', foreignKeys: [fk] }).at(-1)).toBe(
      'ALTER TABLE "z"."u" ADD CONSTRAINT "k" FOREIGN KEY ("x") REFERENCES "s"."p" ("id")'
    )
    expect(copy({ withData: false, foreignKeys: [{ ...fk, refSchema: 'y' }] }).at(-1)).toContain('REFERENCES "y"."p"')
  })

  it('copies several tables under their own names, with the details the preview filled', () => {
    expect(
      pg({
        op: 'copyTables',
        tables: ['a', 'b'],
        toSchema: 'z',
        withData: true,
        details: { a: { columns: ['x'] } },
      })
    ).toEqual([
      'CREATE TABLE "z"."a" (LIKE "s"."a" INCLUDING ALL)',
      'INSERT INTO "z"."a" ("x") OVERRIDING SYSTEM VALUE SELECT "x" FROM "s"."a"',
      'CREATE TABLE "z"."b" (LIKE "s"."b" INCLUDING ALL)',
      'INSERT INTO "z"."b" OVERRIDING SYSTEM VALUE SELECT * FROM "s"."b"',
    ])
    expect(pg({ op: 'copyTables', tables: ['a'], withData: false })).toEqual([
      'CREATE TABLE "s"."a" (LIKE "s"."a" INCLUDING ALL)',
    ])
  })
})

describe('PostgreSQL: routines, triggers and views', () => {
  const routine = (extra: Record<string, unknown> = {}): DdlOp =>
    ({
      op: 'createRoutine',
      kind: 'function',
      name: 'f',
      params: [
        { mode: 'IN', name: 'a', type: 'int' },
        { mode: 'OUT', name: 'b', type: 'text' },
      ],
      returns: 'int',
      body: ' BEGIN RETURN 1; END; ',
      language: 'plpgsql',
      deterministic: false,
      ...extra,
    }) as DdlOp

  it('creates a function with its signature, language, volatility and security, the body dollar-quoted', () => {
    expect(pg(routine())).toEqual([
      'CREATE FUNCTION "s"."f"(IN "a" int, OUT "b" text) RETURNS int LANGUAGE plpgsql AS $body$\nBEGIN RETURN 1; END;\n$body$',
    ])
    expect(pg(routine({ deterministic: true, sqlSecurity: 'DEFINER', language: 'sql', params: [] }))).toEqual([
      'CREATE FUNCTION "s"."f"() RETURNS int LANGUAGE sql IMMUTABLE SECURITY DEFINER AS $body$\nBEGIN RETURN 1; END;\n$body$',
    ])
    expect(pg(routine({ kind: 'procedure', returns: undefined, params: [] }))[0]).toMatch(
      /^CREATE PROCEDURE "s"\."f"\(\) LANGUAGE/
    )
  })

  it('adds a comment on the routine, and refuses a function without a return type or MySQL options', () => {
    expect(pg(routine({ comment: "it's", params: [] }))[1]).toBe(`COMMENT ON FUNCTION "s"."f"() IS 'it''s'`)
    expect(pg(routine({ comment: '', params: [] }))).toHaveLength(1)
    refuses(() => pg(routine({ returns: undefined })), 'UNSUPPORTED', /needs a return type/)
    refuses(() => pg(routine({ definer: { user: 'u', host: 'h' } })), 'UNSUPPORTED', /DEFINER is a MySQL option/)
    refuses(() => pg(routine({ dataAccess: 'NO SQL' })), 'UNSUPPORTED', /data-access characteristic is a MySQL option/)
  })

  it('picks a dollar-quote tag the body does not contain', () => {
    expect(pg(routine({ body: 'SELECT $body$x$body$', params: [] }))[0]).toContain(
      'AS $body1$\nSELECT $body$x$body$\n$body1$'
    )
    expect(pg(routine({ body: 'SELECT $body$x$body$ $body1$', params: [] }))[0]).toContain('AS $body2$')
  })

  it('drops a routine by its parameter list, and alters its security and comment in one transaction', () => {
    expect(pg({ op: 'dropRoutine', kind: 'function', name: 'f', parameters: 'int, text' })).toEqual([
      'DROP FUNCTION "s"."f"(int, text)',
    ])
    expect(pg({ op: 'dropRoutine', kind: 'procedure', name: 'p' })).toEqual(['DROP PROCEDURE "s"."p"()'])
    expect(pg({ op: 'alterRoutine', kind: 'function', name: 'f', parameters: 'int', sqlSecurity: 'INVOKER' })).toEqual([
      'ALTER FUNCTION "s"."f"(int) SECURITY INVOKER',
    ])
    expect(pg({ op: 'alterRoutine', kind: 'procedure', name: 'p', comment: 'c' })).toEqual([
      `COMMENT ON PROCEDURE "s"."p"() IS 'c'`,
    ])
    expect(pg({ op: 'alterRoutine', kind: 'function', name: 'f', comment: '' })).toEqual([
      'COMMENT ON FUNCTION "s"."f"() IS NULL',
    ])
    expect(pg({ op: 'alterRoutine', kind: 'function', name: 'f', sqlSecurity: 'DEFINER', comment: 'c' })).toEqual([
      'BEGIN',
      'ALTER FUNCTION "s"."f"() SECURITY DEFINER',
      `COMMENT ON FUNCTION "s"."f"() IS 'c'`,
      'COMMIT',
    ])
    refuses(() => pg({ op: 'alterRoutine', kind: 'function', name: 'f' }), 'VALIDATION', /No routine characteristic/)
    refuses(
      () => pg({ op: 'alterRoutine', kind: 'function', name: 'f', dataAccess: 'NO SQL', comment: 'c' }),
      'UNSUPPORTED',
      /MySQL option/
    )
  })

  it('replaces a routine in place when its name and parameters stay, else drops the old overload first', () => {
    const replaceOp = (replaces: Record<string, unknown>, extra: Record<string, unknown> = {}) =>
      pg({
        ...(routine({ params: [{ mode: 'IN', name: 'a', type: 'int' }], ...extra }) as object),
        op: 'replaceRoutine',
        replaces,
      } as DdlOp)
    const inPlace = replaceOp({ kind: 'function', name: 'f', parameters: 'IN a integer'.replace('integer', 'int') })
    // One statement needs no transaction around it.
    expect(inPlace).toHaveLength(1)
    expect(inPlace[0]).toMatch(/^CREATE OR REPLACE FUNCTION "s"\."f"/)
    // The catalog may leave out IN and vary spacing and case; that is still the same parameters.
    expect(replaceOp({ kind: 'function', name: 'f', parameters: 'A  INT' })[0]).toMatch(/^CREATE OR REPLACE/)
    // Two parameters, with the modes and spacing the catalog may print: still the same parameters.
    const two = {
      params: [
        { mode: 'IN', name: 'a', type: 'int' },
        { mode: 'IN', name: 'b', type: 'text' },
      ],
    }
    expect(replaceOp({ kind: 'function', name: 'f', parameters: 'IN  a int, b   text' }, two)).toHaveLength(1)
    expect(replaceOp({ kind: 'function', name: 'f', parameters: 'a int' }, two)[1]).toBe('DROP FUNCTION "s"."f"(a int)')
    // No parameters on either side is the same list, and the routine is replaced in place.
    expect(replaceOp({ kind: 'function', name: 'f' }, { params: [] })).toHaveLength(1)
    // A different parameter list, name or kind is another routine: the old one is dropped.
    const other = replaceOp({ kind: 'function', name: 'f', parameters: 'text' })
    expect(other.slice(0, 2)).toEqual(['BEGIN', 'DROP FUNCTION "s"."f"(text)'])
    expect(other[2]).toMatch(/^CREATE FUNCTION/)
    expect(replaceOp({ kind: 'function', name: 'g', parameters: 'a int' })[1]).toBe('DROP FUNCTION "s"."g"(a int)')
    expect(replaceOp({ kind: 'procedure', name: 'f', parameters: 'a int' })[1]).toBe('DROP PROCEDURE "s"."f"(a int)')
    expect(replaceOp({ kind: 'function', name: 'g' })[1]).toBe('DROP FUNCTION "s"."g"()')
  })

  it('creates a trigger with a function named after it, and refuses a definer or any event', () => {
    const trigger = {
      op: 'createTrigger',
      name: 'g',
      table: 't',
      timing: 'AFTER',
      event: 'UPDATE',
      body: ' BEGIN RETURN NEW; END; ',
    } as const
    expect(pg(trigger)).toEqual([
      'CREATE FUNCTION "s"."g_fn"() RETURNS trigger LANGUAGE plpgsql AS $body$\nBEGIN RETURN NEW; END;\n$body$',
      'CREATE TRIGGER "g" AFTER UPDATE ON "s"."t" FOR EACH ROW EXECUTE FUNCTION "s"."g_fn"()',
    ])
    refuses(() => pg({ ...trigger, definer: { user: 'u', host: 'h' } }), 'UNSUPPORTED', /DEFINER is a MySQL option/)
    expect(pg({ op: 'dropTrigger', name: 'g', table: 't' })).toEqual(['DROP TRIGGER "g" ON "s"."t"'])
    for (const op of [
      { op: 'createEvent', name: 'e', schedule: { kind: 'at', at: '2030-01-01 00:00:00' }, body: 'x', enabled: true },
      {
        op: 'replaceEvent',
        replaces: 'o',
        name: 'e',
        schedule: { kind: 'at', at: '2030-01-01 00:00:00' },
        body: 'x',
        enabled: true,
      },
      { op: 'enableEvent', name: 'e' },
      { op: 'disableEvent', name: 'e' },
      { op: 'dropEvent', name: 'e' },
    ] as DdlOp[]) {
      refuses(() => pg(op), 'UNSUPPORTED', /no event scheduler/)
    }
  })

  it('replaces a trigger in one transaction, dropping the old function when the name changes', () => {
    const replace = (name: string, extra: Record<string, unknown> = {}) =>
      pg({
        op: 'replaceTrigger',
        name,
        table: 't',
        timing: 'BEFORE',
        event: 'INSERT',
        body: 'BEGIN RETURN NEW; END',
        replaces: { name: 'g', table: 't' },
        ...extra,
      } as DdlOp)
    const same = replace('g')
    expect(same[0]).toBe('BEGIN')
    expect(same[1]).toBe('DROP TRIGGER "g" ON "s"."t"')
    expect(same[2]).toMatch(/^CREATE OR REPLACE FUNCTION "s"\."g_fn"\(\)/)
    expect(same[3]).toBe('CREATE TRIGGER "g" BEFORE INSERT ON "s"."t" FOR EACH ROW EXECUTE FUNCTION "s"."g_fn"()')
    expect(same.at(-1)).toBe('COMMIT')
    expect(same.some((s) => s.startsWith('DROP FUNCTION'))).toBe(false)
    const renamed = replace('h')
    expect(renamed[2]).toBe('DROP FUNCTION IF EXISTS "s"."g_fn"()')
    expect(renamed[3]).toMatch(/^CREATE OR REPLACE FUNCTION "s"\."h_fn"/)
    refuses(() => replace('g', { definer: { user: 'u', host: 'h' } }), 'UNSUPPORTED', /DEFINER is a MySQL option/)
  })

  it('creates a view, trimming the select, and refuses the MySQL options', () => {
    expect(
      pg({ op: 'createView', name: 'v', select: ' SELECT 1 ; ', orReplace: true, columns: ['a'], checkOption: 'LOCAL' })
    ).toEqual(['CREATE OR REPLACE VIEW "s"."v" ("a") AS SELECT 1\nWITH LOCAL CHECK OPTION'])
    expect(pg({ op: 'createView', name: 'v', select: 'SELECT 1', orReplace: false, columns: ['a', 'b'] })[0]).toContain(
      'VIEW "s"."v" ("a", "b") AS'
    )
    expect(pg({ op: 'createView', name: 'v', select: 'SELECT 1', orReplace: false, columns: [] })).toEqual([
      'CREATE VIEW "s"."v" AS SELECT 1',
    ])
    refuses(
      () => pg({ op: 'createView', name: 'v', select: 'SELECT 1', orReplace: false, algorithm: 'MERGE' }),
      'UNSUPPORTED',
      /ALGORITHM is a MySQL option/
    )
    refuses(
      () =>
        pg({ op: 'createView', name: 'v', select: 'SELECT 1', orReplace: false, definer: { user: 'u', host: 'h' } }),
      'UNSUPPORTED',
      /DEFINER is a MySQL option/
    )
    refuses(
      () => pg({ op: 'createView', name: 'v', select: 'SELECT 1', orReplace: false, sqlSecurity: 'INVOKER' }),
      'UNSUPPORTED',
      /SQL SECURITY is a MySQL option/
    )
  })

  it('replaces by the literal text or by a regular expression with the global flag', () => {
    const base = { op: 'replaceInColumn', table: 't', column: 'c', find: "a'b", replace: 'x' } as const
    expect(pg(base)).toEqual([
      `UPDATE "s"."t" SET "c" = replace("c", 'a''b', 'x') WHERE replace("c", 'a''b', 'x') IS DISTINCT FROM "c"`,
    ])
    expect(pg({ ...base, regex: true })[0]).toContain(`SET "c" = regexp_replace("c", 'a''b', 'x', 'g')`)
    expect(pg({ ...base, regex: false })[0]).toContain('SET "c" = replace(')
  })
})
