import { type TriggerInfo } from '@tsmyadmin/shared'
import { describe, expect, it } from 'vitest'
import { quoteIdent } from '../../sql/quote.ts'
import { AdapterError, type DatabaseAdapter, type RowBatch } from '../../types.ts'
import type { ConformanceEnv } from './env.ts'
import { EXEC, input } from './helpers.ts'

/** Conformance: showCreateTable and iterateRows (in the order they have always run in). */
export function describeDumpAndExport(env: ConformanceEnv): void {
  const { ctx, ns, dialect, scratch, exec, execOk, browseAll, isMariaDb } = env
  describe('showCreateTable', () => {
    it('returns DDL that names the table, and a view definition for views', async () => {
      const users = await env.db.showCreateTable(ns, 'users')
      expect(users.length).toBeGreaterThan(0)
      expect(users[0]).toMatch(/CREATE TABLE/i)
      expect(users.join('\n')).toContain('users')
      const view = await env.db.showCreateTable(ns, 'active_users')
      expect(view.join('\n')).toMatch(/CREATE( OR REPLACE)?[^;]*VIEW/i)
    })

    it('rejects unknown tables', async () => {
      await expect(env.db.showCreateTable(ns, 'nope_nope')).rejects.toMatchObject({ code: 'NOT_FOUND' })
    })

    it.skipIf(dialect !== 'postgres')(
      'keeps CHECK / UNIQUE constraints, deferrable keys, collations, identity options and matview indexes (PostgreSQL)',
      async () => {
        const t = `${scratch}_cons`
        const c = `${scratch}_cons_child`
        const mv = `${scratch}_cons_mv`
        await execOk(
          `CREATE TABLE ${t} (id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 10 CACHE 5) PRIMARY KEY,
             code TEXT COLLATE "C" NOT NULL, n INT CHECK (n BETWEEN 1 AND 100), CONSTRAINT ${t}_code_key UNIQUE (code));
           CREATE TABLE ${c} (id INT PRIMARY KEY, parent INT REFERENCES ${t} (id) DEFERRABLE INITIALLY DEFERRED);
           CREATE MATERIALIZED VIEW ${mv} AS SELECT id FROM ${t}; CREATE UNIQUE INDEX ${mv}_idx ON ${mv} (id)`
        )
        try {
          const parent = (await env.db.showCreateTable(ns, t)).join('\n')
          expect(parent).toContain('GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 10 CACHE 5)')
          expect(parent).toContain('COLLATE "C"')
          expect(parent).toMatch(/ADD CONSTRAINT "[^"]+" CHECK \(+n >= 1\)+ AND \(+n <= 100\)+/)
          expect(parent).toContain(`ADD CONSTRAINT "${t}_code_key" UNIQUE (code)`)
          // The constraint creates its index: no separate CREATE UNIQUE INDEX for it.
          expect(parent).not.toContain(`CREATE UNIQUE INDEX "${t}_code_key"`)
          const child = (await env.db.showCreateTable(ns, c)).join('\n')
          // pg_get_constraintdef text: unquoted plain names, MATCH / actions / DEFERRABLE / NOT VALID kept.
          expect(child).toMatch(/FOREIGN KEY \(parent\) REFERENCES [^\n]* DEFERRABLE INITIALLY DEFERRED$/m)
          const view = (await env.db.showCreateTable(ns, mv)).join('\n')
          expect(view).toContain(`CREATE UNIQUE INDEX ${mv}_idx ON`)
        } finally {
          await execOk(`DROP MATERIALIZED VIEW ${mv}; DROP TABLE ${c}; DROP TABLE ${t}`)
        }
      }
    )

    it.skipIf(dialect !== 'postgres')(
      'keeps FK options, UNLOGGED / storage parameters, inheritance and partitions (PostgreSQL)',
      async () => {
        const p = `${scratch}_parent`
        const ch = `${scratch}_inh_kid`
        const fk = `${scratch}_fkopts`
        const part = `${scratch}_part`
        await execOk(
          `CREATE UNLOGGED TABLE ${p} (a INT, b INT, PRIMARY KEY (a, b), CHECK (a > 0)) WITH (fillfactor = 70);
           CREATE TABLE ${ch} (extra TEXT, b INT NOT NULL DEFAULT 5) INHERITS (${p});
           ALTER TABLE ${ch} ALTER COLUMN a SET DEFAULT 9;
           CREATE UNLOGGED TABLE ${fk} (id INT PRIMARY KEY, a INT DEFAULT 1, b INT DEFAULT 1);
           ALTER TABLE ${fk} ADD CONSTRAINT ${fk}_ab FOREIGN KEY (a, b) REFERENCES ${p} (a, b) MATCH FULL ON DELETE SET DEFAULT ON UPDATE SET NULL NOT VALID;
           CREATE TABLE ${part} (id INT, d DATE) PARTITION BY RANGE (d);
           CREATE TABLE ${part}_2024 PARTITION OF ${part} FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');
           CREATE UNLOGGED TABLE ${part}_rest PARTITION OF ${part} DEFAULT WITH (fillfactor = 60);
           COMMENT ON TABLE ${part}_rest IS 'the rest';
           CREATE INDEX ${part}_d_idx ON ${part} (d);
           CREATE INDEX "${part} spaced" ON ${part} (d);
           CREATE INDEX ${part}_2024_id_idx ON ${part}_2024 (id);
           ALTER TABLE ${part}_2024 ADD CONSTRAINT ${part}_2024_chk CHECK (id > 0);
           ALTER TABLE ${part}_2024 ADD PRIMARY KEY (id, d)`
        )
        try {
          const parent = (await env.db.showCreateTable(ns, p)).join('\n')
          expect(parent).toContain(`CREATE UNLOGGED TABLE "public"."${p}"`)
          expect(parent).toContain("WITH (fillfactor='70')")
          expect((await env.db.describeTable(ns, ch)).inherits).toEqual([p])
          const child = (await env.db.showCreateTable(ns, ch)).join('\n')
          expect(child).toContain(`INHERITS (public.${p})`)
          // The inherited CHECK belongs to the parent: not repeated on the child. Only columns the child declares
          // itself are listed (`b` is redeclared, `a` is not); an inherited column's own default is set afterwards.
          expect(child).not.toContain('CHECK')
          expect(child).not.toMatch(/^\s+"a" integer/m)
          expect(child).toMatch(/^\s+"b" integer NOT NULL DEFAULT 5/m)
          expect(child).toContain(`ALTER TABLE ONLY "public"."${ch}" ALTER COLUMN "a" SET DEFAULT 9`)
          const opts = (await env.db.showCreateTable(ns, fk)).join('\n')
          expect(opts).toContain('MATCH FULL ON UPDATE SET NULL ON DELETE SET DEFAULT NOT VALID')
          const partitioned = await env.db.showCreateTable(ns, part)
          expect(partitioned[0]).toContain('PARTITION BY RANGE (d)')
          expect(partitioned).toContainEqual(
            `CREATE TABLE "public"."${part}_2024" PARTITION OF "public"."${part}" FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')`
          )
          // Leaf attributes: UNLOGGED, storage parameters and the comment live on the partition.
          expect(partitioned).toContainEqual(
            `CREATE UNLOGGED TABLE "public"."${part}_rest" PARTITION OF "public"."${part}" DEFAULT WITH (fillfactor='60')`
          )
          expect(partitioned).toContainEqual(`COMMENT ON TABLE "public"."${part}_rest" IS 'the rest'`)
          expect(partitioned.join('\n')).toMatch(
            new RegExp(`^CREATE INDEX "${part} spaced" ON (?:public\\.)?${part} USING btree \\(d\\)$`, 'm')
          )
          // The parent's index is created without ONLY (so it reaches the partitions); a partition keeps its own
          // index and constraint, but not the ones it inherits from the parent.
          expect(partitioned.join('\n')).toMatch(
            new RegExp(`^CREATE INDEX ${part}_d_idx ON (?:public\\.)?${part} USING btree \\(d\\)$`, 'm')
          )
          expect(partitioned.join('\n')).not.toContain('ON ONLY')
          expect(partitioned).toContainEqual(`CREATE INDEX ${part}_2024_id_idx ON public.${part}_2024 USING btree (id)`)
          expect(partitioned).toContainEqual(
            `ALTER TABLE "public"."${part}_2024" ADD CONSTRAINT "${part}_2024_chk" CHECK ((id > 0))`
          )
          expect(partitioned.join('\n')).not.toContain(`${part}_2024_d_idx`)
          expect(partitioned).toContainEqual(
            `ALTER TABLE "public"."${part}_2024" ADD CONSTRAINT "${part}_2024_pkey" PRIMARY KEY (id, d)`
          )
          // Partitions are not tables of their own in the listing (their rows come through the parent).
          expect((await env.db.listTables(ns)).map((x) => x.name)).not.toContain(`${part}_2024`)
        } finally {
          await execOk(`DROP TABLE ${part}; DROP TABLE ${fk}; DROP TABLE ${ch}; DROP TABLE ${p}`)
        }
      }
    )

    it.skipIf(dialect !== 'mysql')('dumps a MariaDB package as its specification and body', async () => {
      if (!(await isMariaDb())) return
      const p = `${scratch}_pkg`
      // Package bodies hold `;`: created through a DELIMITER block, as a dump would.
      await execOk(
        [
          'SET SESSION sql_mode = ORACLE;',
          'DELIMITER $$',
          `CREATE OR REPLACE PACKAGE ${p} AS FUNCTION f RETURN INT; END$$`,
          `CREATE OR REPLACE PACKAGE BODY ${p} AS FUNCTION f RETURN INT AS BEGIN RETURN 1; END; END$$`,
          'DELIMITER ;',
        ].join('\n')
      )
      try {
        const kinds = (await env.db.listRoutines(ns)).filter((r) => r.name === p).map((r) => r.kind)
        expect(kinds).toEqual(['package', 'package body'])
        expect(await env.db.routineDefinition(ns, p, 'package')).toMatch(/^CREATE .*PACKAGE/)
        expect(await env.db.routineDefinition(ns, p, 'package body')).toMatch(/^CREATE .*PACKAGE BODY/)
      } finally {
        // Each run resets the session, and MariaDB 10.11 parses DROP PACKAGE only in Oracle mode.
        await execOk(`SET SESSION sql_mode = ORACLE;\nDROP PACKAGE ${p}`)
      }
    })

    it.skipIf(dialect !== 'postgres')(
      'keeps partial-index predicates and materialized views (PostgreSQL)',
      async () => {
        const t = `${scratch}_partial`
        const mv = `${t}_mv`
        await execOk(
          `CREATE TABLE ${t} (id INT PRIMARY KEY, email TEXT, deleted_at TIMESTAMP NULL);
         CREATE UNIQUE INDEX ${t}_email_live ON ${t} (email) WHERE deleted_at IS NULL;
         CREATE MATERIALIZED VIEW ${mv} AS SELECT id FROM ${t}`
        )
        try {
          const idx = (await env.db.describeTable(ns, t)).indexes.find((i) => i.name === `${t}_email_live`)
          expect(idx).toMatchObject({ unique: true, predicate: 'deleted_at IS NULL' })
          expect((await env.db.showCreateTable(ns, t)).join('\n')).toMatch(
            /UNIQUE INDEX .* WHERE \(?deleted_at IS NULL\)?/
          )
          const info = (await env.db.listTables(ns)).find((x) => x.name === mv)
          expect(info?.kind).toBe('materialized_view')
          expect((await env.db.describeTable(ns, mv)).kind).toBe('materialized_view')
          expect((await env.db.showCreateTable(ns, mv))[0]).toMatch(/^CREATE MATERIALIZED VIEW/)
          expect((await browseAll(mv)).keyKind).toBe('none')
        } finally {
          await exec(`DROP MATERIALIZED VIEW IF EXISTS ${mv}`, { stopOnError: false })
        }
      }
    )
  })

  describe('iterateRows', () => {
    it('leaves the connection session as it found it after a utc scan', async () => {
      // A scan that asks for UTC sets the session time zone; the connection goes back to the pool, and the next
      // borrower (a browse, an edit) must not read its timestamps in that zone. Each adapter below has a pool of
      // its own, so the connection that did the scan is the one the next call gets.
      const showZone = dialect === 'mysql' ? 'SELECT @@session.time_zone' : 'SHOW TIME ZONE'
      const zoneOf = async (adapter: DatabaseAdapter) => {
        const [r] = await adapter.executeSql(ns, showZone, EXEC)
        return r?.kind === 'rows' ? String(r.result.rows[0]?.[0]) : 'no rows'
      }
      const fresh = ctx.create()
      const scanned = ctx.create()
      try {
        const baseline = await zoneOf(fresh)
        for await (const _ of scanned.iterateRows(ns, 'users', { batchSize: 10, utc: true })) {
          // drained: only the connection afterwards matters
        }
        expect(await zoneOf(scanned)).toBe(baseline)
      } finally {
        await fresh.close()
        await scanned.close()
      }
    })

    it('streams every row in primary-key order across batches', async () => {
      const batches: number[][] = []
      for await (const b of env.db.iterateRows(ns, 'users', { batchSize: 2 }))
        batches.push(b.rows.map((r) => Number(r[0])))
      expect(batches).toEqual([[1, 2], [3, 4], [5]])
    })

    it('pages a composite key with keyset comparisons and never repeats or skips rows', async () => {
      const t = `${scratch}_keyset`
      await execOk(`CREATE TABLE ${t} (a INT NOT NULL, b VARCHAR(10) NOT NULL, v INT NULL, PRIMARY KEY (a, b))`)
      const values: string[] = []
      for (let a = 1; a <= 3; a++) for (const b of ['x', 'y', 'z']) values.push(`(${a}, '${b}', ${a * 10})`)
      await execOk(`INSERT INTO ${t} (a, b, v) VALUES ${values.join(', ')}`)
      const seen: string[] = []
      let batches = 0
      for await (const batch of env.db.iterateRows(ns, t, { batchSize: 4 })) {
        batches++
        for (const r of batch.rows) seen.push(`${r[0]}${r[1]}`)
        expect(batch.columns.map((c) => c.name)).toEqual(['a', 'b', 'v'])
      }
      expect(batches).toBe(3)
      expect(seen).toEqual(['1x', '1y', '1z', '2x', '2y', '2z', '3x', '3y', '3z'])
      await execOk(`DROP TABLE ${t}`)
    })

    it('scans a key-less table in batches and survives a consumer that stops early', async () => {
      const t = `${scratch}_nokey`
      await execOk(`CREATE TABLE ${t} (v INT NULL, s VARCHAR(10) NULL)`)
      const values = Array.from({ length: 11 }, (_, i) => `(${i}, 'r${i}')`)
      await execOk(`INSERT INTO ${t} (v, s) VALUES ${values.join(', ')}`)
      const sizes: number[] = []
      const seen = new Set<number>()
      for await (const batch of env.db.iterateRows(ns, t, { batchSize: 4 })) {
        expect(batch.columns.map((c) => c.name)).toEqual(['v', 's'])
        sizes.push(batch.rows.length)
        for (const r of batch.rows) seen.add(Number(r[0]))
      }
      expect(seen.size).toBe(11)
      expect(sizes.reduce((a, b) => a + b, 0)).toBe(11)
      // A caller that gives up mid-scan (a client closing an export) must not poison the pool.
      for await (const batch of env.db.iterateRows(ns, t, { batchSize: 4 })) {
        expect(batch.rows.length).toBeGreaterThan(0)
        break
      }
      expect((await browseAll(t)).rows).toHaveLength(11)
      // A connection that dies mid-scan ends the iteration with an error instead of hanging it (MySQL streams
      // the scan; PostgreSQL pages with a cursor).
      if (dialect === 'mysql') {
        const slow = `${scratch}_slowv`
        const big = `${scratch}_slowt`
        // 1,331 rows at 10 ms each from a plain scan; the 8 KB padding overflows the server's 16 KB net buffer so
        // rows reach the client while the query is still running (small rows would be flushed only at the end).
        await execOk(`CREATE TABLE ${big} (v INT NULL)`)
        await execOk(`INSERT INTO ${big} (v) SELECT a.v FROM ${t} a, ${t} b, ${t} c`)
        await execOk(`CREATE VIEW ${slow} AS SELECT v, REPEAT('x', 8000) AS pad, SLEEP(0.01) AS z FROM ${big}`)
        try {
          const scan = env.db.iterateRows(ns, slow, { batchSize: 2 })[Symbol.asyncIterator]()
          try {
            await scan.next()
            // Found by its text: MariaDB has no connection attributes, so `self` is not set there.
            const me = (await env.db.listProcesses()).find((p) => (p.query ?? '').includes(slow))
            expect(me).toBeDefined()
            if (me) await env.db.killProcess(me.id)
            // Batches already buffered on the client may still come through; the kill surfaces right after.
            const drain = async (): Promise<string> => {
              for (let i = 0; i < 50; i++) {
                const next = await scan.next().then(
                  (r) => (r.done ? 'ended' : 'batch'),
                  (err: unknown) => (err instanceof AdapterError ? err.code : 'other')
                )
                if (next !== 'batch') return next
              }
              return 'still-flowing'
            }
            const outcome = await Promise.race([
              drain(),
              new Promise<string>((resolve) => setTimeout(() => resolve('timeout'), 8000)),
            ])
            expect(['CONNECTION_FAILED', 'QUERY_FAILED']).toContain(outcome)
            expect((await browseAll(t)).rows).toHaveLength(11)
          } finally {
            await Promise.race([scan.return?.(undefined), new Promise((r) => setTimeout(r, 2000))])
          }
        } finally {
          await execOk(`DROP VIEW ${slow}; DROP TABLE ${big}`)
        }
      }
      // An empty table still reports its columns.
      await execOk(`DELETE FROM ${t}`)
      const empty: RowBatch[] = []
      for await (const batch of env.db.iterateRows(ns, t, { batchSize: 4 })) empty.push(batch)
      expect(empty.map((b) => [b.columns.length, b.rows.length])).toEqual([[2, 0]])
      await execOk(`DROP TABLE ${t}`)
    })

    it.skipIf(dialect !== 'mysql')(
      'keeps a trigger written with database-qualified names database-relative',
      async () => {
        const t = `${scratch}_qtrg`
        const dbq = quoteIdent('mysql', ns.database)
        await execOk(`CREATE TABLE ${t} (id INT PRIMARY KEY, v VARCHAR(10))`)
        await execOk(`CREATE TRIGGER ${dbq}.${t}_bi BEFORE INSERT ON ${dbq}.${t} FOR EACH ROW SET NEW.v = 'x'`)
        try {
          const trigger = (await env.db.listTriggers(ns, t)).find((x) => x.name === `${t}_bi`)
          expect(trigger).toBeDefined()
          const sql = env.db.exporter.trigger(ns, trigger as TriggerInfo, true).sql
          // MariaDB keeps the statement as typed (MySQL normalises it): the dump must not name the database.
          expect(sql).not.toContain(`${ns.database}.`)
          expect(sql).toMatch(/TRIGGER `?\w+_qtrg_bi`? BEFORE INSERT ON `?\w+_qtrg`? FOR EACH ROW/)
        } finally {
          await execOk(`DROP TABLE ${t}`)
        }
      }
    )

    it.skipIf(dialect !== 'postgres')(
      'lists a standalone sequence (not the one behind a serial) and dumps it with its owner and position',
      async () => {
        const seq = `${scratch}_pseq`
        const t = `${scratch}_pseqt`
        const serial = `${scratch}_serialt`
        await execOk(
          `CREATE SEQUENCE ${seq} START 100 INCREMENT 5;
           CREATE TABLE ${t} (id bigint DEFAULT nextval('${seq}') PRIMARY KEY, v text);
           ALTER SEQUENCE ${seq} OWNED BY ${t}.id;
           CREATE TABLE ${serial} (id serial PRIMARY KEY);
           INSERT INTO ${t} (v) VALUES ('a'), ('b')`
        )
        try {
          const listed = await env.db.listTables(ns)
          expect(listed.find((x) => x.name === seq)?.kind).toBe('sequence')
          // A serial's own sequence belongs to its column and is not an object of the listing.
          expect(listed.some((x) => x.name === `${serial}_id_seq`)).toBe(false)
          const schema = await env.db.describeTable(ns, t)
          expect(schema.columns[0]).toMatchObject({ name: 'id', extra: '', default: `nextval('${seq}'::regclass)` })
          expect((await env.db.describeTable(ns, serial)).columns[0]?.extra).toBe('serial')
          expect((await env.db.describeTable(ns, seq)).kind).toBe('sequence')
          const created = await env.db.showCreateTable(ns, seq)
          expect(created[0]).toBe(
            `CREATE SEQUENCE "public"."${seq}" AS bigint INCREMENT BY 5 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100 CACHE 1`
          )
          expect(created[1]).toBe(`ALTER SEQUENCE "public"."${seq}" OWNED BY "public"."${t}"."id"`)
          expect(created[2]).toBe(`SELECT pg_catalog.setval('"public"."${seq}"', 105, true)`)
          // The table keeps its default as written, so the dump restores against the recreated sequence.
          expect((await env.db.showCreateTable(ns, t, schema)).join('\n')).toContain(
            `DEFAULT nextval('${seq}'::regclass)`
          )
          // A serial column that owns a second sequence keeps the options of the one its default calls.
          await execOk(
            `ALTER SEQUENCE ${serial}_id_seq INCREMENT BY 3; CREATE SEQUENCE ${seq}_2 INCREMENT BY 10 OWNED BY ${serial}.id`
          )
          expect((await env.db.showCreateTable(ns, serial)).join('\n')).toContain('AS IDENTITY (INCREMENT BY 3)')
          const advance = env.db.exporter.afterData(ns, await env.db.describeTable(ns, serial))
          expect(advance.join('\n')).toContain(`'${serial}_id_seq'::regclass`)
          // An identity column owning an extra sequence keeps its own options; a serial column whose default was
          // repointed elsewhere is a plain default again, and the sequence it no longer uses is listed.
          await execOk(
            `CREATE TABLE ${t}_ident (id int GENERATED ALWAYS AS IDENTITY (INCREMENT BY 5) PRIMARY KEY);
             CREATE SEQUENCE ${seq}_3 INCREMENT BY 10 MINVALUE 7 OWNED BY ${t}_ident.id;
             ALTER TABLE ${serial} ALTER COLUMN id SET DEFAULT nextval('${seq}')`
          )
          expect((await env.db.showCreateTable(ns, `${t}_ident`)).join('\n')).toContain('AS IDENTITY (INCREMENT BY 5)')
          const repointed = await env.db.describeTable(ns, serial)
          expect(repointed.columns[0]).toMatchObject({ extra: '', default: `nextval('${seq}'::regclass)` })
          expect((await env.db.listTables(ns)).some((x) => x.name === `${serial}_id_seq`)).toBe(true)
        } finally {
          await execOk(
            `DROP TABLE IF EXISTS ${t}_ident; DROP TABLE ${serial}; DROP TABLE ${t}; DROP SEQUENCE IF EXISTS ${seq}`
          )
        }
      }
    )

    it.skipIf(dialect !== 'mysql')(
      'dumps a MariaDB sequence as a sequence and keeps table defaults database-relative',
      async () => {
        if (!(await isMariaDb())) return
        const seq = `${scratch}_sq`
        const t = `${scratch}_sqt`
        await execOk(
          `CREATE SEQUENCE ${seq} START WITH 100; CREATE TABLE ${t} (id INT NOT NULL DEFAULT NEXTVAL(${seq}) PRIMARY KEY)`
        )
        await execOk(`INSERT INTO ${t} () VALUES ()`)
        const listed = await env.db.listTables(ns)
        expect(listed.find((x) => x.name === seq)?.kind).toBe('sequence')
        const create = await env.db.showCreateTable(ns, seq)
        expect(create[0]).toMatch(/^CREATE SEQUENCE/)
        // next_not_cached_value: past the value handed out (the cache size decides by how far).
        expect(Number(/RESTART WITH (\d+)$/.exec(create[1] ?? '')?.[1])).toBeGreaterThanOrEqual(101)
        // The table default names the sequence without the database, so the dump restores anywhere.
        expect((await env.db.showCreateTable(ns, t)).join('\n')).not.toContain(`nextval(\`${ns.database}\``)
        await execOk(`DROP TABLE ${t}; DROP SEQUENCE ${seq}`)
      }
    )

    it.skipIf(dialect !== 'mysql')(
      'lists triggers in execution order so a dump recreates FOLLOWS / PRECEDES',
      async () => {
        const t = `${scratch}_trg`
        await execOk(`CREATE TABLE ${t} (id INT PRIMARY KEY, n INT NOT NULL DEFAULT 0)`)
        await execOk(`CREATE TRIGGER ${t}_a BEFORE INSERT ON ${t} FOR EACH ROW SET NEW.n = NEW.n + 1`)
        await execOk(`CREATE TRIGGER ${t}_0 BEFORE INSERT ON ${t} FOR EACH ROW PRECEDES ${t}_a SET NEW.n = NEW.n * 10`)
        const names = (await env.db.listTriggers(ns, t)).map((x) => x.name)
        expect(names).toEqual([`${t}_0`, `${t}_a`])
        await execOk(`DROP TABLE ${t}`)
      }
    )

    it.skipIf(dialect !== 'mysql')('pages, updates and filters a BIT-keyed table (MySQL / MariaDB)', async () => {
      const t = `${scratch}_bitkey`
      await execOk(`CREATE TABLE ${t} (b BIT(8) NOT NULL PRIMARY KEY, v INT NOT NULL)`)
      await execOk(
        `INSERT INTO ${t} (b, v) VALUES (b'00000000', 0), (b'00000001', 1), (b'00100111', 39), (b'10000000', 128)`
      )
      const seen: number[] = []
      for await (const batch of env.db.iterateRows(ns, t, { batchSize: 1 }))
        for (const r of batch.rows) seen.push(Number(r[1]))
      expect(seen).toEqual([0, 1, 39, 128])
      const rows = await browseAll(t)
      const key = input(rows.rows.find((r) => r[1] === 128)?.[0])
      expect(await env.db.updateRow(ns, t, { kind: 'pk', values: { b: key } }, { v: 129 })).toEqual({ affectedRows: 1 })
      const hit = await env.db.browseRows(ns, t, {
        offset: 0,
        limit: 10,
        sort: [],
        filters: [{ column: 'b', op: 'eq', value: key }],
      })
      expect(hit.rows.map((r) => r[1])).toEqual([129])
      await execOk(`DROP TABLE ${t}`)
    })

    it('pages a composite key with BIGINT values beyond 2^53 exactly', async () => {
      const t = `${scratch}_bigkey`
      await execOk(`CREATE TABLE ${t} (id BIGINT NOT NULL, n INT NOT NULL, PRIMARY KEY (id, n))`)
      await execOk(
        `INSERT INTO ${t} (id, n) VALUES (9223372036854775806, 1), (9223372036854775807, 1), (9223372036854775806, 2), (9007199254740993, 1), (9007199254740992, 1)`
      )
      const seen: string[] = []
      for await (const b of env.db.iterateRows(ns, t, { batchSize: 1 }))
        for (const r of b.rows) seen.push(`${r[0]}/${r[1]}`)
      expect(seen).toEqual([
        '9007199254740992/1',
        '9007199254740993/1',
        '9223372036854775806/1',
        '9223372036854775806/2',
        '9223372036854775807/1',
      ])
      await execOk(`DROP TABLE ${t}`)
    })

    it('pages an ENUM key in a total order that agrees with the keyset comparison', async () => {
      // Labels that differ only by case: a case-insensitive comparison would make them tie and skip one.
      const t = `${scratch}_enumkey`
      if (dialect === 'postgres') await execOk(`CREATE TYPE ${t}_e AS ENUM ('zeta', 'alpha', 'Alpha', 'mid')`)
      const type = dialect === 'mysql' ? "ENUM('zeta', 'alpha', 'Alpha', 'mid') COLLATE utf8mb4_bin" : `${t}_e`
      await execOk(`CREATE TABLE ${t} (e ${type} NOT NULL PRIMARY KEY, n INT NOT NULL)`)
      await execOk(`INSERT INTO ${t} (e, n) VALUES ('zeta', 1), ('alpha', 2), ('Alpha', 4), ('mid', 3)`)
      const seen: string[] = []
      for await (const b of env.db.iterateRows(ns, t, { batchSize: 1 })) for (const r of b.rows) seen.push(String(r[0]))
      expect([...seen].sort()).toEqual(['Alpha', 'alpha', 'mid', 'zeta'])
      expect(seen).toHaveLength(4)
      await execOk(`DROP TABLE ${t}`)
      if (dialect === 'postgres') await execOk(`DROP TYPE ${t}_e`)
    })

    it('leaves the connection clean when the consumer stops early', async () => {
      const it = env.db.iterateRows(ns, 'users', { batchSize: 2 })[Symbol.asyncIterator]()
      expect((await it.next()).done).toBe(false)
      await it.return?.(undefined)
      // The same pooled connection must serve a full export afterwards (no open cursor / transaction).
      let total = 0
      for await (const b of env.db.iterateRows(ns, 'users', { batchSize: 2 })) total += b.rows.length
      expect(total).toBe(5)
      if (dialect === 'postgres') {
        // A leaked transaction is stale; an export in flight elsewhere (between FETCHes) is fresh.
        const idle = await execOk(
          "SELECT count(*) FROM pg_stat_activity WHERE state = 'idle in transaction' AND xact_start < now() - interval '2 seconds'"
        )
        expect(Number(idle[0]?.kind === 'rows' ? idle[0].result.rows[0]?.[0] : -1)).toBe(0)
      }
    })

    it('exports every row of a key-less table exactly once across many batches', async () => {
      const t = `${scratch}_nokey`
      await execOk(`CREATE TABLE ${t} (a INT NOT NULL, b VARCHAR(10) NULL)`)
      const values = Array.from({ length: 1200 }, (_, i) => `(${i}, 'v${i}')`)
      await execOk(`INSERT INTO ${t} (a, b) VALUES ${values.join(', ')}`)
      const seen: number[] = []
      for await (const batch of env.db.iterateRows(ns, t, { batchSize: 7 }))
        for (const r of batch.rows) seen.push(Number(r[0]))
      expect(seen).toHaveLength(1200)
      expect(new Set(seen).size).toBe(1200)
      await execOk(`DROP TABLE ${t}`)
    })

    it('iterates a view (no key: single batch on MySQL, ctid-less on PostgreSQL)', async () => {
      const batches: RowBatch[] = []
      for await (const b of env.db.iterateRows(ns, 'active_users', { batchSize: 2 })) batches.push(b)
      const rows = batches.flatMap((b) => b.rows)
      expect(rows.length).toBeGreaterThan(0)
      expect(batches[0]?.columns.some((c) => c.name === 'name')).toBe(true)
      const insert = env.db.exporter.insert(ns, 'active_users', batches[0]?.columns.map((c) => c.name) ?? [], rows)
      expect(insert).toMatch(/^INSERT INTO/)
    })

    it('handles tables without a key and empty tables', async () => {
      let total = 0
      for await (const b of env.db.iterateRows(ns, 'no_pk', { batchSize: 3 })) total += b.rows.length
      expect(total).toBe(4)
      const empty: { columns: { name: string }[]; rows: unknown[] }[] = []
      for await (const b of env.db.iterateRows(ns, `${scratch}_empty`, { batchSize: 10 })) empty.push(b)
      expect(empty).toHaveLength(1)
      expect(empty[0]?.rows).toEqual([])
      expect(empty[0]?.columns.map((c) => c.name)).toEqual(['id'])
    })
  })
}
