/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProcessesRouteImport } from './routes/_app/processes'
import { Route as AppStatusRouteImport } from './routes/_app/status'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppVariablesRouteImport } from './routes/_app/variables'
import { Route as AppDbDbRouteImport } from './routes/_app/db.$db'
import { Route as AppDbDbIndexRouteImport } from './routes/_app/db.$db/index'
import { Route as AppDbDbExportRouteImport } from './routes/_app/db.$db/export'
import { Route as AppDbDbImportRouteImport } from './routes/_app/db.$db/import'
import { Route as AppDbDbPrivilegesRouteImport } from './routes/_app/db.$db/privileges'
import { Route as AppDbDbSqlRouteImport } from './routes/_app/db.$db/sql'
import { Route as AppDbDbTableTableRouteImport } from './routes/_app/db.$db/table.$table'
import { Route as AppDbDbTableTableIndexRouteImport } from './routes/_app/db.$db/table.$table/index'
import { Route as AppDbDbTableTableExportRouteImport } from './routes/_app/db.$db/table.$table/export'
import { Route as AppDbDbTableTableImportRouteImport } from './routes/_app/db.$db/table.$table/import'
import { Route as AppDbDbTableTableInsertRouteImport } from './routes/_app/db.$db/table.$table/insert'
import { Route as AppDbDbTableTableOperationsRouteImport } from './routes/_app/db.$db/table.$table/operations'
import { Route as AppDbDbTableTableSearchRouteImport } from './routes/_app/db.$db/table.$table/search'
import { Route as AppDbDbTableTableSqlRouteImport } from './routes/_app/db.$db/table.$table/sql'
import { Route as AppDbDbTableTableStructureRouteImport } from './routes/_app/db.$db/table.$table/structure'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessesRoute = AppProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppVariablesRoute = AppVariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => AppRoute,
} as any)
const AppDbDbRoute = AppDbDbRouteImport.update({
  id: '/db/$db',
  path: '/db/$db',
  getParentRoute: () => AppRoute,
} as any)
const AppDbDbIndexRoute = AppDbDbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbExportRoute = AppDbDbExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbImportRoute = AppDbDbImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbPrivilegesRoute = AppDbDbPrivilegesRouteImport.update({
  id: '/privileges',
  path: '/privileges',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbSqlRoute = AppDbDbSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbTableTableRoute = AppDbDbTableTableRouteImport.update({
  id: '/table/$table',
  path: '/table/$table',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbTableTableIndexRoute = AppDbDbTableTableIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableExportRoute = AppDbDbTableTableExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableImportRoute = AppDbDbTableTableImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableInsertRoute = AppDbDbTableTableInsertRouteImport.update({
  id: '/insert',
  path: '/insert',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableOperationsRoute =
  AppDbDbTableTableOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AppDbDbTableTableRoute,
  } as any)
const AppDbDbTableTableSearchRoute = AppDbDbTableTableSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableSqlRoute = AppDbDbTableTableSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableStructureRoute =
  AppDbDbTableTableStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => AppDbDbTableTableRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/processes': typeof AppProcessesRoute
  '/status': typeof AppStatusRoute
  '/users': typeof AppUsersRoute
  '/variables': typeof AppVariablesRoute
  '/db/$db': typeof AppDbDbRouteWithChildren
  '/db/$db/export': typeof AppDbDbExportRoute
  '/db/$db/import': typeof AppDbDbImportRoute
  '/db/$db/privileges': typeof AppDbDbPrivilegesRoute
  '/db/$db/sql': typeof AppDbDbSqlRoute
  '/db/$db/': typeof AppDbDbIndexRoute
  '/db/$db/table/$table': typeof AppDbDbTableTableRouteWithChildren
  '/db/$db/table/$table/export': typeof AppDbDbTableTableExportRoute
  '/db/$db/table/$table/import': typeof AppDbDbTableTableImportRoute
  '/db/$db/table/$table/insert': typeof AppDbDbTableTableInsertRoute
  '/db/$db/table/$table/operations': typeof AppDbDbTableTableOperationsRoute
  '/db/$db/table/$table/search': typeof AppDbDbTableTableSearchRoute
  '/db/$db/table/$table/sql': typeof AppDbDbTableTableSqlRoute
  '/db/$db/table/$table/structure': typeof AppDbDbTableTableStructureRoute
  '/db/$db/table/$table/': typeof AppDbDbTableTableIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/processes': typeof AppProcessesRoute
  '/status': typeof AppStatusRoute
  '/users': typeof AppUsersRoute
  '/variables': typeof AppVariablesRoute
  '/': typeof AppIndexRoute
  '/db/$db/export': typeof AppDbDbExportRoute
  '/db/$db/import': typeof AppDbDbImportRoute
  '/db/$db/privileges': typeof AppDbDbPrivilegesRoute
  '/db/$db/sql': typeof AppDbDbSqlRoute
  '/db/$db': typeof AppDbDbIndexRoute
  '/db/$db/table/$table/export': typeof AppDbDbTableTableExportRoute
  '/db/$db/table/$table/import': typeof AppDbDbTableTableImportRoute
  '/db/$db/table/$table/insert': typeof AppDbDbTableTableInsertRoute
  '/db/$db/table/$table/operations': typeof AppDbDbTableTableOperationsRoute
  '/db/$db/table/$table/search': typeof AppDbDbTableTableSearchRoute
  '/db/$db/table/$table/sql': typeof AppDbDbTableTableSqlRoute
  '/db/$db/table/$table/structure': typeof AppDbDbTableTableStructureRoute
  '/db/$db/table/$table': typeof AppDbDbTableTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/processes': typeof AppProcessesRoute
  '/_app/status': typeof AppStatusRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/variables': typeof AppVariablesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/db/$db': typeof AppDbDbRouteWithChildren
  '/_app/db/$db/export': typeof AppDbDbExportRoute
  '/_app/db/$db/import': typeof AppDbDbImportRoute
  '/_app/db/$db/privileges': typeof AppDbDbPrivilegesRoute
  '/_app/db/$db/sql': typeof AppDbDbSqlRoute
  '/_app/db/$db/': typeof AppDbDbIndexRoute
  '/_app/db/$db/table/$table': typeof AppDbDbTableTableRouteWithChildren
  '/_app/db/$db/table/$table/export': typeof AppDbDbTableTableExportRoute
  '/_app/db/$db/table/$table/import': typeof AppDbDbTableTableImportRoute
  '/_app/db/$db/table/$table/insert': typeof AppDbDbTableTableInsertRoute
  '/_app/db/$db/table/$table/operations': typeof AppDbDbTableTableOperationsRoute
  '/_app/db/$db/table/$table/search': typeof AppDbDbTableTableSearchRoute
  '/_app/db/$db/table/$table/sql': typeof AppDbDbTableTableSqlRoute
  '/_app/db/$db/table/$table/structure': typeof AppDbDbTableTableStructureRoute
  '/_app/db/$db/table/$table/': typeof AppDbDbTableTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/processes'
    | '/status'
    | '/users'
    | '/variables'
    | '/db/$db'
    | '/db/$db/export'
    | '/db/$db/import'
    | '/db/$db/privileges'
    | '/db/$db/sql'
    | '/db/$db/'
    | '/db/$db/table/$table'
    | '/db/$db/table/$table/export'
    | '/db/$db/table/$table/import'
    | '/db/$db/table/$table/insert'
    | '/db/$db/table/$table/operations'
    | '/db/$db/table/$table/search'
    | '/db/$db/table/$table/sql'
    | '/db/$db/table/$table/structure'
    | '/db/$db/table/$table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/processes'
    | '/status'
    | '/users'
    | '/variables'
    | '/'
    | '/db/$db/export'
    | '/db/$db/import'
    | '/db/$db/privileges'
    | '/db/$db/sql'
    | '/db/$db'
    | '/db/$db/table/$table/export'
    | '/db/$db/table/$table/import'
    | '/db/$db/table/$table/insert'
    | '/db/$db/table/$table/operations'
    | '/db/$db/table/$table/search'
    | '/db/$db/table/$table/sql'
    | '/db/$db/table/$table/structure'
    | '/db/$db/table/$table'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/processes'
    | '/_app/status'
    | '/_app/users'
    | '/_app/variables'
    | '/_app/'
    | '/_app/db/$db'
    | '/_app/db/$db/export'
    | '/_app/db/$db/import'
    | '/_app/db/$db/privileges'
    | '/_app/db/$db/sql'
    | '/_app/db/$db/'
    | '/_app/db/$db/table/$table'
    | '/_app/db/$db/table/$table/export'
    | '/_app/db/$db/table/$table/import'
    | '/_app/db/$db/table/$table/insert'
    | '/_app/db/$db/table/$table/operations'
    | '/_app/db/$db/table/$table/search'
    | '/_app/db/$db/table/$table/sql'
    | '/_app/db/$db/table/$table/structure'
    | '/_app/db/$db/table/$table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/processes': {
      id: '/_app/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof AppProcessesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status': {
      id: '/_app/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/variables': {
      id: '/_app/variables'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof AppVariablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db/$db': {
      id: '/_app/db/$db'
      path: '/db/$db'
      fullPath: '/db/$db'
      preLoaderRoute: typeof AppDbDbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db/$db/': {
      id: '/_app/db/$db/'
      path: '/'
      fullPath: '/db/$db/'
      preLoaderRoute: typeof AppDbDbIndexRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/export': {
      id: '/_app/db/$db/export'
      path: '/export'
      fullPath: '/db/$db/export'
      preLoaderRoute: typeof AppDbDbExportRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/import': {
      id: '/_app/db/$db/import'
      path: '/import'
      fullPath: '/db/$db/import'
      preLoaderRoute: typeof AppDbDbImportRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/privileges': {
      id: '/_app/db/$db/privileges'
      path: '/privileges'
      fullPath: '/db/$db/privileges'
      preLoaderRoute: typeof AppDbDbPrivilegesRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/sql': {
      id: '/_app/db/$db/sql'
      path: '/sql'
      fullPath: '/db/$db/sql'
      preLoaderRoute: typeof AppDbDbSqlRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/table/$table': {
      id: '/_app/db/$db/table/$table'
      path: '/table/$table'
      fullPath: '/db/$db/table/$table'
      preLoaderRoute: typeof AppDbDbTableTableRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/table/$table/': {
      id: '/_app/db/$db/table/$table/'
      path: '/'
      fullPath: '/db/$db/table/$table/'
      preLoaderRoute: typeof AppDbDbTableTableIndexRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/export': {
      id: '/_app/db/$db/table/$table/export'
      path: '/export'
      fullPath: '/db/$db/table/$table/export'
      preLoaderRoute: typeof AppDbDbTableTableExportRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/import': {
      id: '/_app/db/$db/table/$table/import'
      path: '/import'
      fullPath: '/db/$db/table/$table/import'
      preLoaderRoute: typeof AppDbDbTableTableImportRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/insert': {
      id: '/_app/db/$db/table/$table/insert'
      path: '/insert'
      fullPath: '/db/$db/table/$table/insert'
      preLoaderRoute: typeof AppDbDbTableTableInsertRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/operations': {
      id: '/_app/db/$db/table/$table/operations'
      path: '/operations'
      fullPath: '/db/$db/table/$table/operations'
      preLoaderRoute: typeof AppDbDbTableTableOperationsRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/search': {
      id: '/_app/db/$db/table/$table/search'
      path: '/search'
      fullPath: '/db/$db/table/$table/search'
      preLoaderRoute: typeof AppDbDbTableTableSearchRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/sql': {
      id: '/_app/db/$db/table/$table/sql'
      path: '/sql'
      fullPath: '/db/$db/table/$table/sql'
      preLoaderRoute: typeof AppDbDbTableTableSqlRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/structure': {
      id: '/_app/db/$db/table/$table/structure'
      path: '/structure'
      fullPath: '/db/$db/table/$table/structure'
      preLoaderRoute: typeof AppDbDbTableTableStructureRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
  }
}

interface AppDbDbTableTableRouteChildren {
  AppDbDbTableTableExportRoute: typeof AppDbDbTableTableExportRoute
  AppDbDbTableTableImportRoute: typeof AppDbDbTableTableImportRoute
  AppDbDbTableTableInsertRoute: typeof AppDbDbTableTableInsertRoute
  AppDbDbTableTableOperationsRoute: typeof AppDbDbTableTableOperationsRoute
  AppDbDbTableTableSearchRoute: typeof AppDbDbTableTableSearchRoute
  AppDbDbTableTableSqlRoute: typeof AppDbDbTableTableSqlRoute
  AppDbDbTableTableStructureRoute: typeof AppDbDbTableTableStructureRoute
  AppDbDbTableTableIndexRoute: typeof AppDbDbTableTableIndexRoute
}

const AppDbDbTableTableRouteChildren: AppDbDbTableTableRouteChildren = {
  AppDbDbTableTableExportRoute: AppDbDbTableTableExportRoute,
  AppDbDbTableTableImportRoute: AppDbDbTableTableImportRoute,
  AppDbDbTableTableInsertRoute: AppDbDbTableTableInsertRoute,
  AppDbDbTableTableOperationsRoute: AppDbDbTableTableOperationsRoute,
  AppDbDbTableTableSearchRoute: AppDbDbTableTableSearchRoute,
  AppDbDbTableTableSqlRoute: AppDbDbTableTableSqlRoute,
  AppDbDbTableTableStructureRoute: AppDbDbTableTableStructureRoute,
  AppDbDbTableTableIndexRoute: AppDbDbTableTableIndexRoute,
}

const AppDbDbTableTableRouteWithChildren =
  AppDbDbTableTableRoute._addFileChildren(AppDbDbTableTableRouteChildren)

interface AppDbDbRouteChildren {
  AppDbDbExportRoute: typeof AppDbDbExportRoute
  AppDbDbImportRoute: typeof AppDbDbImportRoute
  AppDbDbPrivilegesRoute: typeof AppDbDbPrivilegesRoute
  AppDbDbSqlRoute: typeof AppDbDbSqlRoute
  AppDbDbIndexRoute: typeof AppDbDbIndexRoute
  AppDbDbTableTableRoute: typeof AppDbDbTableTableRouteWithChildren
}

const AppDbDbRouteChildren: AppDbDbRouteChildren = {
  AppDbDbExportRoute: AppDbDbExportRoute,
  AppDbDbImportRoute: AppDbDbImportRoute,
  AppDbDbPrivilegesRoute: AppDbDbPrivilegesRoute,
  AppDbDbSqlRoute: AppDbDbSqlRoute,
  AppDbDbIndexRoute: AppDbDbIndexRoute,
  AppDbDbTableTableRoute: AppDbDbTableTableRouteWithChildren,
}

const AppDbDbRouteWithChildren =
  AppDbDbRoute._addFileChildren(AppDbDbRouteChildren)

interface AppRouteChildren {
  AppProcessesRoute: typeof AppProcessesRoute
  AppStatusRoute: typeof AppStatusRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVariablesRoute: typeof AppVariablesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDbDbRoute: typeof AppDbDbRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppProcessesRoute: AppProcessesRoute,
  AppStatusRoute: AppStatusRoute,
  AppUsersRoute: AppUsersRoute,
  AppVariablesRoute: AppVariablesRoute,
  AppIndexRoute: AppIndexRoute,
  AppDbDbRoute: AppDbDbRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
