/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppDbDbRouteImport } from './routes/_app/db.$db'
import { Route as AppDbDbIndexRouteImport } from './routes/_app/db.$db/index'
import { Route as AppDbDbSqlRouteImport } from './routes/_app/db.$db/sql'
import { Route as AppDbDbTableTableRouteImport } from './routes/_app/db.$db/table.$table'
import { Route as AppDbDbTableTableIndexRouteImport } from './routes/_app/db.$db/table.$table/index'
import { Route as AppDbDbTableTableInsertRouteImport } from './routes/_app/db.$db/table.$table/insert'
import { Route as AppDbDbTableTableSearchRouteImport } from './routes/_app/db.$db/table.$table/search'
import { Route as AppDbDbTableTableSqlRouteImport } from './routes/_app/db.$db/table.$table/sql'
import { Route as AppDbDbTableTableStructureRouteImport } from './routes/_app/db.$db/table.$table/structure'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDbDbRoute = AppDbDbRouteImport.update({
  id: '/db/$db',
  path: '/db/$db',
  getParentRoute: () => AppRoute,
} as any)
const AppDbDbIndexRoute = AppDbDbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbSqlRoute = AppDbDbSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbTableTableRoute = AppDbDbTableTableRouteImport.update({
  id: '/table/$table',
  path: '/table/$table',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbTableTableIndexRoute = AppDbDbTableTableIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableInsertRoute = AppDbDbTableTableInsertRouteImport.update({
  id: '/insert',
  path: '/insert',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableSearchRoute = AppDbDbTableTableSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableSqlRoute = AppDbDbTableTableSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableStructureRoute =
  AppDbDbTableTableStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => AppDbDbTableTableRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/db/$db': typeof AppDbDbRouteWithChildren
  '/db/$db/sql': typeof AppDbDbSqlRoute
  '/db/$db/': typeof AppDbDbIndexRoute
  '/db/$db/table/$table': typeof AppDbDbTableTableRouteWithChildren
  '/db/$db/table/$table/insert': typeof AppDbDbTableTableInsertRoute
  '/db/$db/table/$table/search': typeof AppDbDbTableTableSearchRoute
  '/db/$db/table/$table/sql': typeof AppDbDbTableTableSqlRoute
  '/db/$db/table/$table/structure': typeof AppDbDbTableTableStructureRoute
  '/db/$db/table/$table/': typeof AppDbDbTableTableIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/db/$db/sql': typeof AppDbDbSqlRoute
  '/db/$db': typeof AppDbDbIndexRoute
  '/db/$db/table/$table/insert': typeof AppDbDbTableTableInsertRoute
  '/db/$db/table/$table/search': typeof AppDbDbTableTableSearchRoute
  '/db/$db/table/$table/sql': typeof AppDbDbTableTableSqlRoute
  '/db/$db/table/$table/structure': typeof AppDbDbTableTableStructureRoute
  '/db/$db/table/$table': typeof AppDbDbTableTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/db/$db': typeof AppDbDbRouteWithChildren
  '/_app/db/$db/sql': typeof AppDbDbSqlRoute
  '/_app/db/$db/': typeof AppDbDbIndexRoute
  '/_app/db/$db/table/$table': typeof AppDbDbTableTableRouteWithChildren
  '/_app/db/$db/table/$table/insert': typeof AppDbDbTableTableInsertRoute
  '/_app/db/$db/table/$table/search': typeof AppDbDbTableTableSearchRoute
  '/_app/db/$db/table/$table/sql': typeof AppDbDbTableTableSqlRoute
  '/_app/db/$db/table/$table/structure': typeof AppDbDbTableTableStructureRoute
  '/_app/db/$db/table/$table/': typeof AppDbDbTableTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/db/$db'
    | '/db/$db/sql'
    | '/db/$db/'
    | '/db/$db/table/$table'
    | '/db/$db/table/$table/insert'
    | '/db/$db/table/$table/search'
    | '/db/$db/table/$table/sql'
    | '/db/$db/table/$table/structure'
    | '/db/$db/table/$table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/db/$db/sql'
    | '/db/$db'
    | '/db/$db/table/$table/insert'
    | '/db/$db/table/$table/search'
    | '/db/$db/table/$table/sql'
    | '/db/$db/table/$table/structure'
    | '/db/$db/table/$table'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/db/$db'
    | '/_app/db/$db/sql'
    | '/_app/db/$db/'
    | '/_app/db/$db/table/$table'
    | '/_app/db/$db/table/$table/insert'
    | '/_app/db/$db/table/$table/search'
    | '/_app/db/$db/table/$table/sql'
    | '/_app/db/$db/table/$table/structure'
    | '/_app/db/$db/table/$table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db/$db': {
      id: '/_app/db/$db'
      path: '/db/$db'
      fullPath: '/db/$db'
      preLoaderRoute: typeof AppDbDbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db/$db/': {
      id: '/_app/db/$db/'
      path: '/'
      fullPath: '/db/$db/'
      preLoaderRoute: typeof AppDbDbIndexRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/sql': {
      id: '/_app/db/$db/sql'
      path: '/sql'
      fullPath: '/db/$db/sql'
      preLoaderRoute: typeof AppDbDbSqlRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/table/$table': {
      id: '/_app/db/$db/table/$table'
      path: '/table/$table'
      fullPath: '/db/$db/table/$table'
      preLoaderRoute: typeof AppDbDbTableTableRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/table/$table/': {
      id: '/_app/db/$db/table/$table/'
      path: '/'
      fullPath: '/db/$db/table/$table/'
      preLoaderRoute: typeof AppDbDbTableTableIndexRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/insert': {
      id: '/_app/db/$db/table/$table/insert'
      path: '/insert'
      fullPath: '/db/$db/table/$table/insert'
      preLoaderRoute: typeof AppDbDbTableTableInsertRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/search': {
      id: '/_app/db/$db/table/$table/search'
      path: '/search'
      fullPath: '/db/$db/table/$table/search'
      preLoaderRoute: typeof AppDbDbTableTableSearchRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/sql': {
      id: '/_app/db/$db/table/$table/sql'
      path: '/sql'
      fullPath: '/db/$db/table/$table/sql'
      preLoaderRoute: typeof AppDbDbTableTableSqlRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/structure': {
      id: '/_app/db/$db/table/$table/structure'
      path: '/structure'
      fullPath: '/db/$db/table/$table/structure'
      preLoaderRoute: typeof AppDbDbTableTableStructureRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
  }
}

interface AppDbDbTableTableRouteChildren {
  AppDbDbTableTableInsertRoute: typeof AppDbDbTableTableInsertRoute
  AppDbDbTableTableSearchRoute: typeof AppDbDbTableTableSearchRoute
  AppDbDbTableTableSqlRoute: typeof AppDbDbTableTableSqlRoute
  AppDbDbTableTableStructureRoute: typeof AppDbDbTableTableStructureRoute
  AppDbDbTableTableIndexRoute: typeof AppDbDbTableTableIndexRoute
}

const AppDbDbTableTableRouteChildren: AppDbDbTableTableRouteChildren = {
  AppDbDbTableTableInsertRoute: AppDbDbTableTableInsertRoute,
  AppDbDbTableTableSearchRoute: AppDbDbTableTableSearchRoute,
  AppDbDbTableTableSqlRoute: AppDbDbTableTableSqlRoute,
  AppDbDbTableTableStructureRoute: AppDbDbTableTableStructureRoute,
  AppDbDbTableTableIndexRoute: AppDbDbTableTableIndexRoute,
}

const AppDbDbTableTableRouteWithChildren =
  AppDbDbTableTableRoute._addFileChildren(AppDbDbTableTableRouteChildren)

interface AppDbDbRouteChildren {
  AppDbDbSqlRoute: typeof AppDbDbSqlRoute
  AppDbDbIndexRoute: typeof AppDbDbIndexRoute
  AppDbDbTableTableRoute: typeof AppDbDbTableTableRouteWithChildren
}

const AppDbDbRouteChildren: AppDbDbRouteChildren = {
  AppDbDbSqlRoute: AppDbDbSqlRoute,
  AppDbDbIndexRoute: AppDbDbIndexRoute,
  AppDbDbTableTableRoute: AppDbDbTableTableRouteWithChildren,
}

const AppDbDbRouteWithChildren =
  AppDbDbRoute._addFileChildren(AppDbDbRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDbDbRoute: typeof AppDbDbRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDbDbRoute: AppDbDbRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
