/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCollationsRouteImport } from './routes/_app/collations'
import { Route as AppEnginesRouteImport } from './routes/_app/engines'
import { Route as AppPluginsRouteImport } from './routes/_app/plugins'
import { Route as AppProcessesRouteImport } from './routes/_app/processes'
import { Route as AppReplicationRouteImport } from './routes/_app/replication'
import { Route as AppSecurityRouteImport } from './routes/_app/security'
import { Route as AppSqlRouteImport } from './routes/_app/sql'
import { Route as AppStatusRouteImport } from './routes/_app/status'
import { Route as AppUserGroupsRouteImport } from './routes/_app/user-groups'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppVariablesRouteImport } from './routes/_app/variables'
import { Route as AppDbDbRouteImport } from './routes/_app/db.$db'
import { Route as AppDbDbIndexRouteImport } from './routes/_app/db.$db/index'
import { Route as AppDbDbCentralRouteImport } from './routes/_app/db.$db/central'
import { Route as AppDbDbDesignerRouteImport } from './routes/_app/db.$db/designer'
import { Route as AppDbDbEventsRouteImport } from './routes/_app/db.$db/events'
import { Route as AppDbDbExportRouteImport } from './routes/_app/db.$db/export'
import { Route as AppDbDbImportRouteImport } from './routes/_app/db.$db/import'
import { Route as AppDbDbOperationsRouteImport } from './routes/_app/db.$db/operations'
import { Route as AppDbDbPrivilegesRouteImport } from './routes/_app/db.$db/privileges'
import { Route as AppDbDbQueryRouteImport } from './routes/_app/db.$db/query'
import { Route as AppDbDbRoutinesRouteImport } from './routes/_app/db.$db/routines'
import { Route as AppDbDbSearchRouteImport } from './routes/_app/db.$db/search'
import { Route as AppDbDbSqlRouteImport } from './routes/_app/db.$db/sql'
import { Route as AppDbDbTrackingRouteImport } from './routes/_app/db.$db/tracking'
import { Route as AppDbDbTriggersRouteImport } from './routes/_app/db.$db/triggers'
import { Route as AppDbDbTableTableRouteImport } from './routes/_app/db.$db/table.$table'
import { Route as AppDbDbTableTableIndexRouteImport } from './routes/_app/db.$db/table.$table/index'
import { Route as AppDbDbTableTableExportRouteImport } from './routes/_app/db.$db/table.$table/export'
import { Route as AppDbDbTableTableImportRouteImport } from './routes/_app/db.$db/table.$table/import'
import { Route as AppDbDbTableTableInsertRouteImport } from './routes/_app/db.$db/table.$table/insert'
import { Route as AppDbDbTableTableOperationsRouteImport } from './routes/_app/db.$db/table.$table/operations'
import { Route as AppDbDbTableTablePrivilegesRouteImport } from './routes/_app/db.$db/table.$table/privileges'
import { Route as AppDbDbTableTableSearchRouteImport } from './routes/_app/db.$db/table.$table/search'
import { Route as AppDbDbTableTableSqlRouteImport } from './routes/_app/db.$db/table.$table/sql'
import { Route as AppDbDbTableTableStructureRouteImport } from './routes/_app/db.$db/table.$table/structure'
import { Route as AppDbDbTableTableTrackingRouteImport } from './routes/_app/db.$db/table.$table/tracking'
import { Route as AppDbDbTableTableTriggersRouteImport } from './routes/_app/db.$db/table.$table/triggers'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollationsRoute = AppCollationsRouteImport.update({
  id: '/collations',
  path: '/collations',
  getParentRoute: () => AppRoute,
} as any)
const AppEnginesRoute = AppEnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => AppRoute,
} as any)
const AppPluginsRoute = AppPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessesRoute = AppProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AppRoute,
} as any)
const AppReplicationRoute = AppReplicationRouteImport.update({
  id: '/replication',
  path: '/replication',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSqlRoute = AppSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRoute,
} as any)
const AppUserGroupsRoute = AppUserGroupsRouteImport.update({
  id: '/user-groups',
  path: '/user-groups',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppVariablesRoute = AppVariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => AppRoute,
} as any)
const AppDbDbRoute = AppDbDbRouteImport.update({
  id: '/db/$db',
  path: '/db/$db',
  getParentRoute: () => AppRoute,
} as any)
const AppDbDbIndexRoute = AppDbDbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbCentralRoute = AppDbDbCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbDesignerRoute = AppDbDbDesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbEventsRoute = AppDbDbEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbExportRoute = AppDbDbExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbImportRoute = AppDbDbImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbOperationsRoute = AppDbDbOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbPrivilegesRoute = AppDbDbPrivilegesRouteImport.update({
  id: '/privileges',
  path: '/privileges',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbQueryRoute = AppDbDbQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbRoutinesRoute = AppDbDbRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbSearchRoute = AppDbDbSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbSqlRoute = AppDbDbSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbTrackingRoute = AppDbDbTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbTriggersRoute = AppDbDbTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbTableTableRoute = AppDbDbTableTableRouteImport.update({
  id: '/table/$table',
  path: '/table/$table',
  getParentRoute: () => AppDbDbRoute,
} as any)
const AppDbDbTableTableIndexRoute = AppDbDbTableTableIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableExportRoute = AppDbDbTableTableExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableImportRoute = AppDbDbTableTableImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableInsertRoute = AppDbDbTableTableInsertRouteImport.update({
  id: '/insert',
  path: '/insert',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableOperationsRoute =
  AppDbDbTableTableOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AppDbDbTableTableRoute,
  } as any)
const AppDbDbTableTablePrivilegesRoute =
  AppDbDbTableTablePrivilegesRouteImport.update({
    id: '/privileges',
    path: '/privileges',
    getParentRoute: () => AppDbDbTableTableRoute,
  } as any)
const AppDbDbTableTableSearchRoute = AppDbDbTableTableSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableSqlRoute = AppDbDbTableTableSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => AppDbDbTableTableRoute,
} as any)
const AppDbDbTableTableStructureRoute =
  AppDbDbTableTableStructureRouteImport.update({
    id: '/structure',
    path: '/structure',
    getParentRoute: () => AppDbDbTableTableRoute,
  } as any)
const AppDbDbTableTableTrackingRoute =
  AppDbDbTableTableTrackingRouteImport.update({
    id: '/tracking',
    path: '/tracking',
    getParentRoute: () => AppDbDbTableTableRoute,
  } as any)
const AppDbDbTableTableTriggersRoute =
  AppDbDbTableTableTriggersRouteImport.update({
    id: '/triggers',
    path: '/triggers',
    getParentRoute: () => AppDbDbTableTableRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/collations': typeof AppCollationsRoute
  '/engines': typeof AppEnginesRoute
  '/plugins': typeof AppPluginsRoute
  '/processes': typeof AppProcessesRoute
  '/replication': typeof AppReplicationRoute
  '/security': typeof AppSecurityRoute
  '/sql': typeof AppSqlRoute
  '/status': typeof AppStatusRoute
  '/user-groups': typeof AppUserGroupsRoute
  '/users': typeof AppUsersRoute
  '/variables': typeof AppVariablesRoute
  '/db/$db': typeof AppDbDbRouteWithChildren
  '/db/$db/central': typeof AppDbDbCentralRoute
  '/db/$db/designer': typeof AppDbDbDesignerRoute
  '/db/$db/events': typeof AppDbDbEventsRoute
  '/db/$db/export': typeof AppDbDbExportRoute
  '/db/$db/import': typeof AppDbDbImportRoute
  '/db/$db/operations': typeof AppDbDbOperationsRoute
  '/db/$db/privileges': typeof AppDbDbPrivilegesRoute
  '/db/$db/query': typeof AppDbDbQueryRoute
  '/db/$db/routines': typeof AppDbDbRoutinesRoute
  '/db/$db/search': typeof AppDbDbSearchRoute
  '/db/$db/sql': typeof AppDbDbSqlRoute
  '/db/$db/tracking': typeof AppDbDbTrackingRoute
  '/db/$db/triggers': typeof AppDbDbTriggersRoute
  '/db/$db/': typeof AppDbDbIndexRoute
  '/db/$db/table/$table': typeof AppDbDbTableTableRouteWithChildren
  '/db/$db/table/$table/export': typeof AppDbDbTableTableExportRoute
  '/db/$db/table/$table/import': typeof AppDbDbTableTableImportRoute
  '/db/$db/table/$table/insert': typeof AppDbDbTableTableInsertRoute
  '/db/$db/table/$table/operations': typeof AppDbDbTableTableOperationsRoute
  '/db/$db/table/$table/privileges': typeof AppDbDbTableTablePrivilegesRoute
  '/db/$db/table/$table/search': typeof AppDbDbTableTableSearchRoute
  '/db/$db/table/$table/sql': typeof AppDbDbTableTableSqlRoute
  '/db/$db/table/$table/structure': typeof AppDbDbTableTableStructureRoute
  '/db/$db/table/$table/tracking': typeof AppDbDbTableTableTrackingRoute
  '/db/$db/table/$table/triggers': typeof AppDbDbTableTableTriggersRoute
  '/db/$db/table/$table/': typeof AppDbDbTableTableIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/collations': typeof AppCollationsRoute
  '/engines': typeof AppEnginesRoute
  '/plugins': typeof AppPluginsRoute
  '/processes': typeof AppProcessesRoute
  '/replication': typeof AppReplicationRoute
  '/security': typeof AppSecurityRoute
  '/sql': typeof AppSqlRoute
  '/status': typeof AppStatusRoute
  '/user-groups': typeof AppUserGroupsRoute
  '/users': typeof AppUsersRoute
  '/variables': typeof AppVariablesRoute
  '/': typeof AppIndexRoute
  '/db/$db/central': typeof AppDbDbCentralRoute
  '/db/$db/designer': typeof AppDbDbDesignerRoute
  '/db/$db/events': typeof AppDbDbEventsRoute
  '/db/$db/export': typeof AppDbDbExportRoute
  '/db/$db/import': typeof AppDbDbImportRoute
  '/db/$db/operations': typeof AppDbDbOperationsRoute
  '/db/$db/privileges': typeof AppDbDbPrivilegesRoute
  '/db/$db/query': typeof AppDbDbQueryRoute
  '/db/$db/routines': typeof AppDbDbRoutinesRoute
  '/db/$db/search': typeof AppDbDbSearchRoute
  '/db/$db/sql': typeof AppDbDbSqlRoute
  '/db/$db/tracking': typeof AppDbDbTrackingRoute
  '/db/$db/triggers': typeof AppDbDbTriggersRoute
  '/db/$db': typeof AppDbDbIndexRoute
  '/db/$db/table/$table/export': typeof AppDbDbTableTableExportRoute
  '/db/$db/table/$table/import': typeof AppDbDbTableTableImportRoute
  '/db/$db/table/$table/insert': typeof AppDbDbTableTableInsertRoute
  '/db/$db/table/$table/operations': typeof AppDbDbTableTableOperationsRoute
  '/db/$db/table/$table/privileges': typeof AppDbDbTableTablePrivilegesRoute
  '/db/$db/table/$table/search': typeof AppDbDbTableTableSearchRoute
  '/db/$db/table/$table/sql': typeof AppDbDbTableTableSqlRoute
  '/db/$db/table/$table/structure': typeof AppDbDbTableTableStructureRoute
  '/db/$db/table/$table/tracking': typeof AppDbDbTableTableTrackingRoute
  '/db/$db/table/$table/triggers': typeof AppDbDbTableTableTriggersRoute
  '/db/$db/table/$table': typeof AppDbDbTableTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/collations': typeof AppCollationsRoute
  '/_app/engines': typeof AppEnginesRoute
  '/_app/plugins': typeof AppPluginsRoute
  '/_app/processes': typeof AppProcessesRoute
  '/_app/replication': typeof AppReplicationRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/sql': typeof AppSqlRoute
  '/_app/status': typeof AppStatusRoute
  '/_app/user-groups': typeof AppUserGroupsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/variables': typeof AppVariablesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/db/$db': typeof AppDbDbRouteWithChildren
  '/_app/db/$db/central': typeof AppDbDbCentralRoute
  '/_app/db/$db/designer': typeof AppDbDbDesignerRoute
  '/_app/db/$db/events': typeof AppDbDbEventsRoute
  '/_app/db/$db/export': typeof AppDbDbExportRoute
  '/_app/db/$db/import': typeof AppDbDbImportRoute
  '/_app/db/$db/operations': typeof AppDbDbOperationsRoute
  '/_app/db/$db/privileges': typeof AppDbDbPrivilegesRoute
  '/_app/db/$db/query': typeof AppDbDbQueryRoute
  '/_app/db/$db/routines': typeof AppDbDbRoutinesRoute
  '/_app/db/$db/search': typeof AppDbDbSearchRoute
  '/_app/db/$db/sql': typeof AppDbDbSqlRoute
  '/_app/db/$db/tracking': typeof AppDbDbTrackingRoute
  '/_app/db/$db/triggers': typeof AppDbDbTriggersRoute
  '/_app/db/$db/': typeof AppDbDbIndexRoute
  '/_app/db/$db/table/$table': typeof AppDbDbTableTableRouteWithChildren
  '/_app/db/$db/table/$table/export': typeof AppDbDbTableTableExportRoute
  '/_app/db/$db/table/$table/import': typeof AppDbDbTableTableImportRoute
  '/_app/db/$db/table/$table/insert': typeof AppDbDbTableTableInsertRoute
  '/_app/db/$db/table/$table/operations': typeof AppDbDbTableTableOperationsRoute
  '/_app/db/$db/table/$table/privileges': typeof AppDbDbTableTablePrivilegesRoute
  '/_app/db/$db/table/$table/search': typeof AppDbDbTableTableSearchRoute
  '/_app/db/$db/table/$table/sql': typeof AppDbDbTableTableSqlRoute
  '/_app/db/$db/table/$table/structure': typeof AppDbDbTableTableStructureRoute
  '/_app/db/$db/table/$table/tracking': typeof AppDbDbTableTableTrackingRoute
  '/_app/db/$db/table/$table/triggers': typeof AppDbDbTableTableTriggersRoute
  '/_app/db/$db/table/$table/': typeof AppDbDbTableTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/collations'
    | '/engines'
    | '/plugins'
    | '/processes'
    | '/replication'
    | '/security'
    | '/sql'
    | '/status'
    | '/user-groups'
    | '/users'
    | '/variables'
    | '/db/$db'
    | '/db/$db/central'
    | '/db/$db/designer'
    | '/db/$db/events'
    | '/db/$db/export'
    | '/db/$db/import'
    | '/db/$db/operations'
    | '/db/$db/privileges'
    | '/db/$db/query'
    | '/db/$db/routines'
    | '/db/$db/search'
    | '/db/$db/sql'
    | '/db/$db/tracking'
    | '/db/$db/triggers'
    | '/db/$db/'
    | '/db/$db/table/$table'
    | '/db/$db/table/$table/export'
    | '/db/$db/table/$table/import'
    | '/db/$db/table/$table/insert'
    | '/db/$db/table/$table/operations'
    | '/db/$db/table/$table/privileges'
    | '/db/$db/table/$table/search'
    | '/db/$db/table/$table/sql'
    | '/db/$db/table/$table/structure'
    | '/db/$db/table/$table/tracking'
    | '/db/$db/table/$table/triggers'
    | '/db/$db/table/$table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/collations'
    | '/engines'
    | '/plugins'
    | '/processes'
    | '/replication'
    | '/security'
    | '/sql'
    | '/status'
    | '/user-groups'
    | '/users'
    | '/variables'
    | '/'
    | '/db/$db/central'
    | '/db/$db/designer'
    | '/db/$db/events'
    | '/db/$db/export'
    | '/db/$db/import'
    | '/db/$db/operations'
    | '/db/$db/privileges'
    | '/db/$db/query'
    | '/db/$db/routines'
    | '/db/$db/search'
    | '/db/$db/sql'
    | '/db/$db/tracking'
    | '/db/$db/triggers'
    | '/db/$db'
    | '/db/$db/table/$table/export'
    | '/db/$db/table/$table/import'
    | '/db/$db/table/$table/insert'
    | '/db/$db/table/$table/operations'
    | '/db/$db/table/$table/privileges'
    | '/db/$db/table/$table/search'
    | '/db/$db/table/$table/sql'
    | '/db/$db/table/$table/structure'
    | '/db/$db/table/$table/tracking'
    | '/db/$db/table/$table/triggers'
    | '/db/$db/table/$table'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/collations'
    | '/_app/engines'
    | '/_app/plugins'
    | '/_app/processes'
    | '/_app/replication'
    | '/_app/security'
    | '/_app/sql'
    | '/_app/status'
    | '/_app/user-groups'
    | '/_app/users'
    | '/_app/variables'
    | '/_app/'
    | '/_app/db/$db'
    | '/_app/db/$db/central'
    | '/_app/db/$db/designer'
    | '/_app/db/$db/events'
    | '/_app/db/$db/export'
    | '/_app/db/$db/import'
    | '/_app/db/$db/operations'
    | '/_app/db/$db/privileges'
    | '/_app/db/$db/query'
    | '/_app/db/$db/routines'
    | '/_app/db/$db/search'
    | '/_app/db/$db/sql'
    | '/_app/db/$db/tracking'
    | '/_app/db/$db/triggers'
    | '/_app/db/$db/'
    | '/_app/db/$db/table/$table'
    | '/_app/db/$db/table/$table/export'
    | '/_app/db/$db/table/$table/import'
    | '/_app/db/$db/table/$table/insert'
    | '/_app/db/$db/table/$table/operations'
    | '/_app/db/$db/table/$table/privileges'
    | '/_app/db/$db/table/$table/search'
    | '/_app/db/$db/table/$table/sql'
    | '/_app/db/$db/table/$table/structure'
    | '/_app/db/$db/table/$table/tracking'
    | '/_app/db/$db/table/$table/triggers'
    | '/_app/db/$db/table/$table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collations': {
      id: '/_app/collations'
      path: '/collations'
      fullPath: '/collations'
      preLoaderRoute: typeof AppCollationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/engines': {
      id: '/_app/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof AppEnginesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plugins': {
      id: '/_app/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof AppPluginsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/processes': {
      id: '/_app/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof AppProcessesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/replication': {
      id: '/_app/replication'
      path: '/replication'
      fullPath: '/replication'
      preLoaderRoute: typeof AppReplicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sql': {
      id: '/_app/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof AppSqlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status': {
      id: '/_app/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user-groups': {
      id: '/_app/user-groups'
      path: '/user-groups'
      fullPath: '/user-groups'
      preLoaderRoute: typeof AppUserGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/variables': {
      id: '/_app/variables'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof AppVariablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db/$db': {
      id: '/_app/db/$db'
      path: '/db/$db'
      fullPath: '/db/$db'
      preLoaderRoute: typeof AppDbDbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db/$db/': {
      id: '/_app/db/$db/'
      path: '/'
      fullPath: '/db/$db/'
      preLoaderRoute: typeof AppDbDbIndexRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/central': {
      id: '/_app/db/$db/central'
      path: '/central'
      fullPath: '/db/$db/central'
      preLoaderRoute: typeof AppDbDbCentralRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/designer': {
      id: '/_app/db/$db/designer'
      path: '/designer'
      fullPath: '/db/$db/designer'
      preLoaderRoute: typeof AppDbDbDesignerRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/events': {
      id: '/_app/db/$db/events'
      path: '/events'
      fullPath: '/db/$db/events'
      preLoaderRoute: typeof AppDbDbEventsRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/export': {
      id: '/_app/db/$db/export'
      path: '/export'
      fullPath: '/db/$db/export'
      preLoaderRoute: typeof AppDbDbExportRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/import': {
      id: '/_app/db/$db/import'
      path: '/import'
      fullPath: '/db/$db/import'
      preLoaderRoute: typeof AppDbDbImportRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/operations': {
      id: '/_app/db/$db/operations'
      path: '/operations'
      fullPath: '/db/$db/operations'
      preLoaderRoute: typeof AppDbDbOperationsRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/privileges': {
      id: '/_app/db/$db/privileges'
      path: '/privileges'
      fullPath: '/db/$db/privileges'
      preLoaderRoute: typeof AppDbDbPrivilegesRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/query': {
      id: '/_app/db/$db/query'
      path: '/query'
      fullPath: '/db/$db/query'
      preLoaderRoute: typeof AppDbDbQueryRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/routines': {
      id: '/_app/db/$db/routines'
      path: '/routines'
      fullPath: '/db/$db/routines'
      preLoaderRoute: typeof AppDbDbRoutinesRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/search': {
      id: '/_app/db/$db/search'
      path: '/search'
      fullPath: '/db/$db/search'
      preLoaderRoute: typeof AppDbDbSearchRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/sql': {
      id: '/_app/db/$db/sql'
      path: '/sql'
      fullPath: '/db/$db/sql'
      preLoaderRoute: typeof AppDbDbSqlRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/tracking': {
      id: '/_app/db/$db/tracking'
      path: '/tracking'
      fullPath: '/db/$db/tracking'
      preLoaderRoute: typeof AppDbDbTrackingRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/triggers': {
      id: '/_app/db/$db/triggers'
      path: '/triggers'
      fullPath: '/db/$db/triggers'
      preLoaderRoute: typeof AppDbDbTriggersRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/table/$table': {
      id: '/_app/db/$db/table/$table'
      path: '/table/$table'
      fullPath: '/db/$db/table/$table'
      preLoaderRoute: typeof AppDbDbTableTableRouteImport
      parentRoute: typeof AppDbDbRoute
    }
    '/_app/db/$db/table/$table/': {
      id: '/_app/db/$db/table/$table/'
      path: '/'
      fullPath: '/db/$db/table/$table/'
      preLoaderRoute: typeof AppDbDbTableTableIndexRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/export': {
      id: '/_app/db/$db/table/$table/export'
      path: '/export'
      fullPath: '/db/$db/table/$table/export'
      preLoaderRoute: typeof AppDbDbTableTableExportRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/import': {
      id: '/_app/db/$db/table/$table/import'
      path: '/import'
      fullPath: '/db/$db/table/$table/import'
      preLoaderRoute: typeof AppDbDbTableTableImportRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/insert': {
      id: '/_app/db/$db/table/$table/insert'
      path: '/insert'
      fullPath: '/db/$db/table/$table/insert'
      preLoaderRoute: typeof AppDbDbTableTableInsertRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/operations': {
      id: '/_app/db/$db/table/$table/operations'
      path: '/operations'
      fullPath: '/db/$db/table/$table/operations'
      preLoaderRoute: typeof AppDbDbTableTableOperationsRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/privileges': {
      id: '/_app/db/$db/table/$table/privileges'
      path: '/privileges'
      fullPath: '/db/$db/table/$table/privileges'
      preLoaderRoute: typeof AppDbDbTableTablePrivilegesRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/search': {
      id: '/_app/db/$db/table/$table/search'
      path: '/search'
      fullPath: '/db/$db/table/$table/search'
      preLoaderRoute: typeof AppDbDbTableTableSearchRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/sql': {
      id: '/_app/db/$db/table/$table/sql'
      path: '/sql'
      fullPath: '/db/$db/table/$table/sql'
      preLoaderRoute: typeof AppDbDbTableTableSqlRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/structure': {
      id: '/_app/db/$db/table/$table/structure'
      path: '/structure'
      fullPath: '/db/$db/table/$table/structure'
      preLoaderRoute: typeof AppDbDbTableTableStructureRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/tracking': {
      id: '/_app/db/$db/table/$table/tracking'
      path: '/tracking'
      fullPath: '/db/$db/table/$table/tracking'
      preLoaderRoute: typeof AppDbDbTableTableTrackingRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
    '/_app/db/$db/table/$table/triggers': {
      id: '/_app/db/$db/table/$table/triggers'
      path: '/triggers'
      fullPath: '/db/$db/table/$table/triggers'
      preLoaderRoute: typeof AppDbDbTableTableTriggersRouteImport
      parentRoute: typeof AppDbDbTableTableRoute
    }
  }
}

interface AppDbDbTableTableRouteChildren {
  AppDbDbTableTableExportRoute: typeof AppDbDbTableTableExportRoute
  AppDbDbTableTableImportRoute: typeof AppDbDbTableTableImportRoute
  AppDbDbTableTableInsertRoute: typeof AppDbDbTableTableInsertRoute
  AppDbDbTableTableOperationsRoute: typeof AppDbDbTableTableOperationsRoute
  AppDbDbTableTablePrivilegesRoute: typeof AppDbDbTableTablePrivilegesRoute
  AppDbDbTableTableSearchRoute: typeof AppDbDbTableTableSearchRoute
  AppDbDbTableTableSqlRoute: typeof AppDbDbTableTableSqlRoute
  AppDbDbTableTableStructureRoute: typeof AppDbDbTableTableStructureRoute
  AppDbDbTableTableTrackingRoute: typeof AppDbDbTableTableTrackingRoute
  AppDbDbTableTableTriggersRoute: typeof AppDbDbTableTableTriggersRoute
  AppDbDbTableTableIndexRoute: typeof AppDbDbTableTableIndexRoute
}

const AppDbDbTableTableRouteChildren: AppDbDbTableTableRouteChildren = {
  AppDbDbTableTableExportRoute: AppDbDbTableTableExportRoute,
  AppDbDbTableTableImportRoute: AppDbDbTableTableImportRoute,
  AppDbDbTableTableInsertRoute: AppDbDbTableTableInsertRoute,
  AppDbDbTableTableOperationsRoute: AppDbDbTableTableOperationsRoute,
  AppDbDbTableTablePrivilegesRoute: AppDbDbTableTablePrivilegesRoute,
  AppDbDbTableTableSearchRoute: AppDbDbTableTableSearchRoute,
  AppDbDbTableTableSqlRoute: AppDbDbTableTableSqlRoute,
  AppDbDbTableTableStructureRoute: AppDbDbTableTableStructureRoute,
  AppDbDbTableTableTrackingRoute: AppDbDbTableTableTrackingRoute,
  AppDbDbTableTableTriggersRoute: AppDbDbTableTableTriggersRoute,
  AppDbDbTableTableIndexRoute: AppDbDbTableTableIndexRoute,
}

const AppDbDbTableTableRouteWithChildren =
  AppDbDbTableTableRoute._addFileChildren(AppDbDbTableTableRouteChildren)

interface AppDbDbRouteChildren {
  AppDbDbCentralRoute: typeof AppDbDbCentralRoute
  AppDbDbDesignerRoute: typeof AppDbDbDesignerRoute
  AppDbDbEventsRoute: typeof AppDbDbEventsRoute
  AppDbDbExportRoute: typeof AppDbDbExportRoute
  AppDbDbImportRoute: typeof AppDbDbImportRoute
  AppDbDbOperationsRoute: typeof AppDbDbOperationsRoute
  AppDbDbPrivilegesRoute: typeof AppDbDbPrivilegesRoute
  AppDbDbQueryRoute: typeof AppDbDbQueryRoute
  AppDbDbRoutinesRoute: typeof AppDbDbRoutinesRoute
  AppDbDbSearchRoute: typeof AppDbDbSearchRoute
  AppDbDbSqlRoute: typeof AppDbDbSqlRoute
  AppDbDbTrackingRoute: typeof AppDbDbTrackingRoute
  AppDbDbTriggersRoute: typeof AppDbDbTriggersRoute
  AppDbDbIndexRoute: typeof AppDbDbIndexRoute
  AppDbDbTableTableRoute: typeof AppDbDbTableTableRouteWithChildren
}

const AppDbDbRouteChildren: AppDbDbRouteChildren = {
  AppDbDbCentralRoute: AppDbDbCentralRoute,
  AppDbDbDesignerRoute: AppDbDbDesignerRoute,
  AppDbDbEventsRoute: AppDbDbEventsRoute,
  AppDbDbExportRoute: AppDbDbExportRoute,
  AppDbDbImportRoute: AppDbDbImportRoute,
  AppDbDbOperationsRoute: AppDbDbOperationsRoute,
  AppDbDbPrivilegesRoute: AppDbDbPrivilegesRoute,
  AppDbDbQueryRoute: AppDbDbQueryRoute,
  AppDbDbRoutinesRoute: AppDbDbRoutinesRoute,
  AppDbDbSearchRoute: AppDbDbSearchRoute,
  AppDbDbSqlRoute: AppDbDbSqlRoute,
  AppDbDbTrackingRoute: AppDbDbTrackingRoute,
  AppDbDbTriggersRoute: AppDbDbTriggersRoute,
  AppDbDbIndexRoute: AppDbDbIndexRoute,
  AppDbDbTableTableRoute: AppDbDbTableTableRouteWithChildren,
}

const AppDbDbRouteWithChildren =
  AppDbDbRoute._addFileChildren(AppDbDbRouteChildren)

interface AppRouteChildren {
  AppCollationsRoute: typeof AppCollationsRoute
  AppEnginesRoute: typeof AppEnginesRoute
  AppPluginsRoute: typeof AppPluginsRoute
  AppProcessesRoute: typeof AppProcessesRoute
  AppReplicationRoute: typeof AppReplicationRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSqlRoute: typeof AppSqlRoute
  AppStatusRoute: typeof AppStatusRoute
  AppUserGroupsRoute: typeof AppUserGroupsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVariablesRoute: typeof AppVariablesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDbDbRoute: typeof AppDbDbRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCollationsRoute: AppCollationsRoute,
  AppEnginesRoute: AppEnginesRoute,
  AppPluginsRoute: AppPluginsRoute,
  AppProcessesRoute: AppProcessesRoute,
  AppReplicationRoute: AppReplicationRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSqlRoute: AppSqlRoute,
  AppStatusRoute: AppStatusRoute,
  AppUserGroupsRoute: AppUserGroupsRoute,
  AppUsersRoute: AppUsersRoute,
  AppVariablesRoute: AppVariablesRoute,
  AppIndexRoute: AppIndexRoute,
  AppDbDbRoute: AppDbDbRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
